insert into servidores (matricula, email_servidor, nome_completo) values
(	2459760	, 'ana-rodrigues@defensoria.rs.gov.br', 	'ANA IZABEL MENEZES CHÚ'),
(	2699532	, 'tatiana-rodrigues@defensoria.rs.gov.br', 	'TATIANA M. DO NASCIMENTO RODRIGUES'),
(	2714515	, 'marcelo-felin@defensoria.rs.gov.br', 	'MARCELO FRANÇOIS FELIN'),
(	2806835	, 'juliano-amaral@defensoria.rs.gov.br', 	'JULIANO GREFF AMARAL'),
(	2887878	, 'juliana-martins@defensoria.rs.gov.br', 	'JULIANA DA SILVA MARTINS'),
(	3040526	, 'marcelo-blanco@defensoria.rs.gov.br', 	'MARCELO ANDRES BLANCO'),
(	3086291	, 'thiago-lobato@defensoria.rs.gov.br', 	'THIAGO BATAIOLI LOBATO'),
(	3091430	, 'luciana-silva@defensoria.rs.gov.br', 	'LUCIANA PINTO DA SILVA'),
(	3389766	, 'camila-mello@defensoria.rs.gov.br', 	'CAMILA SILVA BANDEIRA DE MELLO'),
(	3401758	, 'marilia-santos@defensoria.rs.gov.br', 	'MARILIA ANDRADE DOS SANTOS'),
(	3403700	, 'claudia-rocha@defensoria.rs.gov.br', 	'CLAUDIA ALVES DA ROCHA'),
(	3405117	, 'martha-silveira@defensoria.rs.gov.br', 	'MARTHA SILVEIRA DA SILVEIRA'),
(	3410765	, 'michel-muller@defensoria.rs.gov.br', 	'MICHEL MULLER'),
(	3417247	, 'ana-gomes@defensoria.rs.gov.br', 	'ANA LUÍSA GODOY GOMES'),
(	3418448	, 'daniela-silva@defensoria.rs.gov.br', 	'DANIELA FRANCO REIS E SILVA'),
(	3440214	, 'aline-monteiro@defensoria.rs.gov.br', 	'ALINE RODRIGUES MONTEIRO'),
(	3440346	, 'alicia-walcher@defensoria.rs.gov.br', 	'ALICIA IREBA HERNANDEZ WALCHER'),
(	3444015	, 'thiago-terra@defensoria.rs.gov.br', 	'THIAGO TWEEDIE TERRA'),
(	3446921	, 'patricia-lourenzon@defensoria.rs.gov.br', 	'PATRICIA MIRANDA LOURENZON'),
(	3452034	, 'daiana-pommerening@defensoria.rs.gov.br', 	'DAIANA TESSMANN POMMERENING'),
(	3529770	, 'bianca-dullius@defensoria.rs.gov.br', 	'BIANCA FRANCINI DULLIUS'),
(	3577589	, 'carolina-denardin@defensoria.rs.gov.br', 	'CAROLINA CANTARUTTI DENARDIN'),
(	3589285	, 'karen-lima@defensoria.rs.gov.br', 	'KAREN PEREIRA DE LIMA'),
(	3602133	, 'renan-guimaraes@defensoria.rs.gov.br', 	'RENAN ESCHILETTI MACHADO GUIMARÃES'),
(	3624358	, 'daiane-brum@defensoria.rs.gov.br', 	'DAIANE DA SILVEIRA BRUM'),
(	3635627	, 'diego-gabiatti@defensoria.rs.gov.br', 	'DIEGO GABIATTI'),
(	3643557	, 'julia-magdalena@defensoria.rs.gov.br', 	'JULIA GUIMARÃES DE MAGDALENA'),
(	3757641	, 'fabio-rachelle@defensoria.rs.gov.br', 	'FÁBIO SILVEIRA RACHELLE'),
(	3788083	, 'aline-drago@defensoria.rs.gov.br', 	'ALINE FAVERZANI DRAGO'),
(	3801306	, 'rafaela-thiesen@defensoria.rs.gov.br', 	'RAFAELA DALABILIA THIESEN'),
(	3802531	, 'douglas-santin@defensoria.rs.gov.br', 	'DOUGLAS ROBERTO WINKEL SANTIN'),
(	3811271	, 'fernando-cintra@defensoria.rs.gov.br', 	'FERNANDO VOGEL CINTRA'),
(	3814920	, 'aline-rocha@defensoria.rs.gov.br', 	'ALINE ORTIZ DA ROCHA'),
(	3824160	, 'valeria-silva@defensoria.rs.gov.br', 	'VALÉRIA SANTIAGO SILVA'),
(	3846075	, 'rodrigo-goncalves@defensoria.rs.gov.br', 	'RODRIGO JUNG GONÇALVES'),
(	3857735	, 'ana-silveira@defensoria.rs.gov.br', 	'ANA CAROLINA RAMOS SILVEIRA'),
(	3859800	, 'aline-machado@defensoria.rs.gov.br', 	'ALINE MACHADO'),
(	3859819	, 'ricardo-portela@defensoria.rs.gov.br', 	'RICARDO SCORSATTO PORTELA'),
(	3859916	, 'juliana-alves@defensoria.rs.gov.br', 	'JULIANA GARCIA ALVES'),
(	3862941	, 'lucas-kalikowski@defensoria.rs.gov.br', 	'LUCAS VERFE KALIKOWSKI'),
(	3871533	, 'cintia-ribeiro@defensoria.rs.gov.br', 	'CÍNTIA FRANÇA RIBEIRO'),
(	3871541	, 'luana-iserhard@defensoria.rs.gov.br', 	'LUANA BORBA ISERHARD'),
(	3878139	, 'jonathan-grellert@defensoria.rs.gov.br', 	'JONATHAN REHBEIN GRELLERT'),
(	3879992	, 'paula-altmann@defensoria.rs.gov.br', 	'PAULA ALTMANN'),
(	3880397	, 'tobiasbassotto@defensoria.rs.gov.br', 	'TOBIAS RADAELLI BASSOTTO'),
(	3880753	, 'camila-santos@defensoria.rs.gov.br', 	'CAMILA CARTIER DOS SANTOS'),
(	3880990	, 'joao-sales@defensoria.rs.gov.br', 	'JOÃO VICENTE FERREIRA CAVALHEIRO SALES'),
(	3881334	, 'leticia-lieberknecht@defensoria.rs.gov.br', 	'LETICIA LUIZA LIEBERKNECHT'),
(	3895505	, 'flavio-junior@defensoria.rs.gov.br', 	'FLAVIO MARTINS RODRIGUES JUNIOR'),
(	3895637	, 'daiane-strack@defensoria.rs.gov.br', 	'DAIANE KLOCKNER STRACK'),
(	3895670	, 'eduardo-silva@defensoria.rs.gov.br', 	'EDUARDO MACHADO SILVA'),
(	3895700	, 'gabriela-scheeren@defensoria.rs.gov.br', 	'GABRIELA SCHEEREN'),
(	3895947	, 'marcell-silva@defensoria.rs.gov.br', 	'MARCELL DO AMARAL SILVA'),
(	3902315	, 'alana-brixner@defensoria.rs.gov.br', 	'ALANA EVELINE BRIXNER'),
(	3904873	, 'adrian-tapada@defensoria.rs.gov.br', 	'ADRIAN ABI TAPADA'),
(	3922243	, 'cristiane-reis@defensoria.rs.gov.br', 	'CRISTIANE AZEVEDO DOS REIS'),
(	3925226	, 'bruno-liedtke@defensoria.rs.gov.br', 	'BRUNO LIEDTKE'),
(	3925668	, 'fernando-araujo@defensoria.rs.gov.br', 	'FERNANDO SANGOI ARAÚJO'),
(	3937534	, 'daniela-luca@defensoria.rs.gov.br', 	'DANIELA DE LUCA'),
(	3939499	, 'rodrigo-bueno@defensoria.rs.gov.br', 	'RODRIGO GALVÃO BUENO'),
(	3941604	, 'andreia-rocha@defensoria.rs.gov.br', 	'ANDREIA ALVES ROCHA'),
(	3941680	, 'caio-paiva@defensoria.rs.gov.br', 	'CAIO EDUARDO LUGRIS PAIVA'),
(	3941728	, 'cassiano-mendes@defensoria.rs.gov.br', 	'CASSIANO GONÇALVES MENDES'),
(	3941779	, 'claudia-karsburg@defensoria.rs.gov.br', 	'CLAUDIA DA ROSA KARSBURG'),
(	3941795	, 'elisa-bosner@defensoria.rs.gov.br', 	'ELISA RUMI BOSNER'),
(	3941809	, 'eloisa-mangini@defensoria.rs.gov.br', 	'ELOISA MANGINI'),
(	3941817	, 'angela-genro@defensoria.rs.gov.br', 	'ANGELA SAIDELES GENRO'),
(	3941833	, 'fernanda-goldenfum@defensoria.rs.gov.br', 	'FERNANDA PEIXOTO GOLDENFUM'),
(	3941841	, 'gustavo-knopp@defensoria.rs.gov.br', 	'GUSTAVO CARLOS COUTO KNOPP'),
(	3941884	, 'leticia-rue@defensoria.rs.gov.br', 	'LETÍCIA ALMEIDA DE LA RUE'),
(	3941892	, 'gustavo-jesus@defensoria.rs.gov.br', 	'GUSTAVO ALVES DE JESUS'),
(	3941914	, 'pamela-rosa@defensoria.rs.gov.br', 	'PAMELA CAROLINE DA ROSA'),
(	3941965	, 'arthur-azambuja@defensoria.rs.gov.br', 	'ARTHUR DE AZAMBUJA'),
(	3942104	, 'roberta-santos@defensoria.rs.gov.br', 	'ROBERTA ANTONIOLI SÓ DOS SANTOS'),
(	3942163	, 'krystoffer-bakof@defensoria.rs.gov.br', 	'KRYSTOFFER ROQUE BAKOF'),
(	3942694	, 'ana-pereira@defensoria.rs.gov.br', 	'ANA PAULA VARGAS PEREIRA'),
(	3942791	, 'leonardo-aurich@defensoria.rs.gov.br', 	'LEONARDO AURICH'),
(	3942830	, 'flavia-mattos@defensoria.rs.gov.br', 	'FLÁVIA DE MELO DA ROCHA MATTOS'),
(	3942953	, 'carla-sousa@defensoria.rs.gov.br', 	'CARLA VERENA DO NASCIMENTO SOUSA'),
(	3943062	, 'elis-miranda@defensoria.rs.gov.br', 	'ELIS REGINA DE SOUSA MIRANDA'),
(	3943194	, 'larissa-agnol@defensoria.rs.gov.br', 	'LARISSA AVENA DALL AGNOL'),
(	3963837	, 'sara-dockhorn@defensoria.rs.gov.br', 	'SARA ELIZE DE ALMEIDA DOCKHORN'),
(	3967069	, 'jussara-abrao@defensoria.rs.gov.br', 	'JUSSARA FERREIRA ABRÃO MACIEL'),
(	3967140	, 'jose-junior@defensoria.rs.gov.br', 	'JOSÉ CARLOS MORAES TRINDADE JÚNIOR'),
(	3968502	, 'aline-silva@defensoria.rs.gov.br', 	'ALINE AMARAL DA SILVA'),
(	3971945	, 'alessandra-francisco@defensoria.rs.gov.br', 	'ALESSANDRA GIL FRANCISCO'),
(	3971996	, 'ana-brandao@defensoria.rs.gov.br', 	'ANA FLÁVIA COSTA BRANDÃO'),
(	3972151	, 'bibiana-lucas@defensoria.rs.gov.br', 	'BIBIANA DE BORBA LUCAS'),
(	3972186	, 'carla-alimena@defensoria.rs.gov.br', 	'CARLA MARRONE ALIMENA'),
(	3972313	, 'carolina-moraes@defensoria.rs.gov.br', 	'CAROLINA FELKER MORAES'),
(	3972356	, 'carlos-pozzer@defensoria.rs.gov.br', 	'CARLOS LUTZ POZZER'),
(	3972399	, 'clair-ferreira@defensoria.rs.gov.br', 	'CLAIR BALHEGO FERREIRA'),
(	3972470	, 'dante-melero@defensoria.rs.gov.br', 	'DANTE LISANDRO DE OLIVEIRA MELERO'),
(	3972488	, 'edegar-junior@defensoria.rs.gov.br', 	'EDEGAR RIBEIRO JÚNIOR'),
(	3972496	, 'everton-gaspar@defensoria.rs.gov.br', 	'EVERTON GASPAR'),
(	4197836	, 'felipe-franceschette@defensoria.rs.gov.br', 	'FELIPE RENE FRANCESCHETTE'),
(	4197895	, 'guilherme-thome@defensoria.rs.gov.br', 	'GUILHERME BISÓL THOMÉ'),
(	4197917	, 'gustavo-bertoldi@defensoria.rs.gov.br', 	'GUSTAVO FONSECA BERTOLDI'),
(	4199057	, 'lenise-santos@defensoria.rs.gov.br', 	'LENISE ALVES SANTOS'),
(	4199081	, 'luana-dalosto@defensoria.rs.gov.br', 	'LUANA DALOSTO'),
(	4199103	, 'lucciele-lanza@defensoria.rs.gov.br', 	'LUCCIELE SILVA LANZA'),
(	4199111	, 'rafael-haas@defensoria.rs.gov.br', 	'RAFAEL CRIVELARO HAAS'),
(	4199146	, 'luiza-przybylski@defensoria.rs.gov.br', 	'LUIZA NORTHFLEET PRZYBYLSKI'),
(	4199162	, 'marcelly-signoretti@defensoria.rs.gov.br', 	'MARCELLY CHRISTIANE GOULART SIGNORETTI'),
(	4199170	, 'regis-silva@defensoria.rs.gov.br', 	'RÉGIS SCHNEIDER DA SILVA'),
(	4199189	, 'marcio-fagundes@defensoria.rs.gov.br', 	'MARCIO NASCIMENTO FAGUNDES'),
(	4199197	, 'renata-fontoura@defensoria.rs.gov.br', 	'RENATA GABRIELA HECKLER DA FONTOURA'),
(	4199227	, 'rodrigo-borba@defensoria.rs.gov.br', 	'RODRIGO ALVES BORBA'),
(	4199251	, 'rute-mello@defensoria.rs.gov.br', 	'RUTE ANTUNES DE MELLO'),
(	4199308	, 'tatiane-spironello@defensoria.rs.gov.br', 	'TATIANE AZEVEDO SPIRONELLO'),
(	4199332	, 'mariane-ceconello@defensoria.rs.gov.br', 	'MARIANE TRAVI CECONELLO'),
(	4199391	, 'nidiara-medeiros@defensoria.rs.gov.br', 	'NIDIARA DENARDI MEDEIROS'),
(	4199529	, 'bruna-farias@defensoria.rs.gov.br', 	'BRUNA PEREIRA FARIAS'),
(	4199545	, 'camila-lago@defensoria.rs.gov.br', 	'CAMILA DAL LAGO'),
(	4199553	, 'douglas-souza@defensoria.rs.gov.br', 	'DOUGLAS LIMA DE SOUZA'),
(	4199561	, 'thales-lang@defensoria.rs.gov.br', 	'THALES KATSUO SAITO LANG'),
(	4199588	, 'tiago-martins@defensoria.rs.gov.br', 	'TIAGO MARTINS DOS SANTOS'),
(	4199600	, 'fernando-taschetto@defensoria.rs.gov.br', 	'FERNANDO MAICON PRADO TASCHETTO'),
(	4199634	, 'laura-silveira@defensoria.rs.gov.br', 	'LAURA PEREIRA DA SILVEIRA'),
(	4199669	, 'nathalia-gonzales@defensoria.rs.gov.br', 	'NATHALIA NASCIMENTO ECOS GONZALES'),
(	4199855	, 'samuel-costa@defensoria.rs.gov.br', 	'SAMUEL TELLES COSTA'),
(	4199928	, 'yasha-gallazzi@defensoria.rs.gov.br', 	'YASHÁ JOSÉ RIZZANTE GALLAZZI'),
(	4199944	, 'vanessa-nicolao@defensoria.rs.gov.br', 	'VANESSA NICOLAO'),
(	4208188	, 'vinicius-basso@defensoria.rs.gov.br', 	'VINICIUS BASSO DOS SANTOS'),
(	4214803	, 'aquila-carvalho@defensoria.rs.gov.br', 	'ÁQUILA DE PAULA POSTIGUILHONE CARVALHO'),
(	4214900	, 'josiel-vicente@defensoria.rs.gov.br', 	'JOSIEL VICENTE'),
(	4214919	, 'marilia-gazal@defensoria.rs.gov.br', 	'MARÍLIA DE OLIVEIRA GAZAL'),
(	4214951	, 'rafael-arsand@defensoria.rs.gov.br', 	'RAFAEL ARSAND'),
(	4214960	, 'rodrigo-weirich@defensoria.rs.gov.br', 	'RODRIGO AHLERT WEIRICH'),
(	4214986	, 'liara-terra@defensoria.rs.gov.br', 	'LIARA JAMILI DUARTE TERRA'),
(	4215001	, 'victor-franco@defensoria.rs.gov.br', 	'VICTOR CARNIATO FRANCO'),
(	4215036	, 'vinicius-mendonca@defensoria.rs.gov.br', 	'VINÍCIUS MOREIRA MENDONÇA'),
(	4215648	, 'matheus-carazzo@defensoria.rs.gov.br', 	'MATHEUS SCHAFER CARAZZO'),
(	4222610	, 'aline-guillante@defensoria.rs.gov.br', 	'ALINE GUILLANTE'),
(	4222644	, 'bianca-hartwig@defensoria.rs.gov.br', 	'BIANCA CENTURION HARTWIG'),
(	4222652	, 'camila-mansur@defensoria.rs.gov.br', 	'CAMILA BELTRAME MANSUR'),
(	4222660	, 'clenio-gabe@defensoria.rs.gov.br', 	'CLENIO LUIS GABE'),
(	4222679	, 'cristian-porto@defensoria.rs.gov.br', 	'CRISTIAN RIBEIRO PORTO'),
(	4222687	, 'fabiano-ferreira@defensoria.rs.gov.br', 	'FABIANO ANDRÉ FERREIRA'),
(	4222695	, 'fernando-morsch@defensoria.rs.gov.br', 	'FERNANDO ALVES MORSCH'),
(	4222709	, 'luan-vanzetto@defensoria.rs.gov.br', 	'LUAN VANZETTO'),
(	4222717	, 'renata-reckziegel@defensoria.rs.gov.br', 	'RENATA BORBA RECKZIEGEL'),
(	4222725	, 'kleiton-matos@defensoria.rs.gov.br', 	'KLEITON DA SILVA MATOS'),
(	4222741	, 'betina-adami@defensoria.rs.gov.br', 	'BETINA DA SILVA ADAMI'),
(	4222750	, 'fernando-rodrigues@defensoria.rs.gov.br', 	'FERNANDO HENRIQUE MELLO RODRIGUES'),
(	4222776	, 'gerdano-neto@defensoria.rs.gov.br', 	'GERDANO DE ABREU NETO'),
(	4222784	, 'lorena-martins@defensoria.rs.gov.br', 	'LORENA SAMPAIO MESQUITA MARTINS'),
(	4222806	, 'karen-floriano@defensoria.rs.gov.br', 	'KAREN CRISTINA LIMA FLORIANO'),
(	4222822	, 'patricia-perpetuo@defensoria.rs.gov.br', 	'PATRÍCIA DAL-BÓ FORTE PERPÉTUO'),
(	4222830	, 'renato-liska@defensoria.rs.gov.br', 	'RENATO COSTAMILAN LISKA'),
(	4222865	, 'cezar-rodrigues@defensoria.rs.gov.br', 	'CEZAR AUGUSTO GALLEGO RODRIGUES'),
(	4227174	, 'olga-tamoto@defensoria.rs.gov.br', 	'OLGA TAMOTO'),
(	4227190	, 'thales-peixoto@defensoria.rs.gov.br', 	'THALES SANTIAGO PEIXOTO'),
(	4228421	, 'vitor-cunha@defensoria.rs.gov.br', 	'VÍTOR COSTA DA CUNHA'),
(	4230701	, 'debora-jesus@defensoria.rs.gov.br', 	'DEBÓRA VANESS LANDVOIGT DE JESUS');

--SELECT '('
--      ,[matricula]
--      ,', '''+[email_servidor]+''', '
--      ,''''+[nome_completo]+'''),'
--  FROM [db_removal_new_3].[dbo].[servidores]