insert into servidores (matricula, email_servidor, nome_completo) values
(	1483838	,	'tatiana-fogaca@defensoria.rs.gov.br'	,	'TATIANA MARA FOGAÇA'	),
(	2634112	,	'richard-noble@defensoria.rs.gov.br'	,	'RICHARD DA SILVA NOBLE'	),
(	2754363	,	'rozinei-diniz@defensoria.rs.gov.br'	,	'ROZINEI DA SILVA DINIZ'	),
(	2771900	,	'valquiria-zorzanello@defensoria.rs.gov.br'	,	'VALQUIRIA BISPO ZORZANELLO'	),
(	2803135	,	'andreia-reis@defensoria.rs.gov.br'	,	'ANDRÉIA VILLAMIL REIS'	),
(	3033651	,	'joao-junior@defensoria.rs.gov.br'	,	'JOÃO LÚCIO MONTEIRO DE SOUZA JUNIOR'	),
(	3402940	,	'siselbach@yahoo.com.br'	,	'SIMONE SELBACH'	),
(	3504859	,	'thomas-vieira@defensoria.rs.gov.br'	,	'THOMAS NICOLAS VIEIRA'	),
(	3608239	,	'heitor-pienis@defensoria.rs.gov.br'	,	'HEITOR MARCOS PIENIS'	),
(	3683990	,	'daiane-benetti@defensoria.rs.gov.br'	,	'DAIANE BENETTI'	),
(	3722635	,	'ramon-alves@defensoria.rs.gov.br'	,	'RAMON PINTO ALVES'	),
(	3878317	,	'tanise-oliveira@defensoria.rs.gov.br'	,	'TANISE PIRES DE OLIVEIRA'	),
(	3878368	,	'jessica-bauer@defensoria.rs.gov.br'	,	'JÉSSICA DOS REIS BAUER'	),
(	3878384	,	'cristina-farias@defensoria.rs.gov.br'	,	'CRISTINA FARIAS'	),
(	3878430	,	'vinicius-santos@defensoria.rs.gov.br'	,	'VINICIUS NAHAN DOS SANTOS'	),
(	3878449	,	'ronei999gold@gmail.com'	,	'RONEI DA SILVA ALMEIDA'	),
(	3878813	,	'juliana-laitartt@defensoria.rs.gov.br'	,	'JULIANA RABELO CAMPOS LAITARTT'	),
(	3878821	,	'regina-carvalho@defensoria.rs.gov.br'	,	'REGINA GÜTLER CARVALHO'	),
(	3878856	,	'carlos-junior@defensoria.rs.gov.br'	,	'CARLOS AUGUSTO LOPES JUNIOR'	),
(	3880044	,	'alexandre-matos@defensoria.rs.gov.br'	,	'ALEXANDRE LEANDRO PADIAS DE MATOS'	),
(	3880052	,	'marcelo-balbom@defensoria.rs.gov.br'	,	'MARCELO MARIN BALBOM'	),
(	3880346	,	'veyzon-muniz@defensoria.rs.gov.br'	,	'VEYZON CAMPOS MUNIZ'	),
(	3880354	,	'lisiane-vieira@defensoria.rs.gov.br'	,	'LISIANE GONÇALVES RIVERO VIEIRA'	),
(	3880575	,	'mathias-silva@defensoria.rs.gov.br'	,	'MATHIAS JANOVIK DA SILVA'	),
(	3880583	,	'matheus-trindade@defensoria.rs.gov.br'	,	'MATHEUS TRINDADE'	),
(	3880613	,	'maria-gomes@defensoria.rs.gov.br'	,	'MARIA GABRIELA GOMES'	),
(	3880672	,	'livia-lima@defensoria.rs.gov.br'	,	'LÍVIA SUCHY LIMA'	),
(	3880761	,	'daniel-vieira@defensoria.rs.gov.br'	,	'DANIEL MOREIRA VIEIRA'	),
(	3880770	,	'mariana-marchi@defensoria.rs.gov.br'	,	'MARIANA FIGUERA MARCHI'	),
(	3880800	,	'marco-rodrigues@defensoria.rs.gov.br'	,	'MARCO ANTONIO DE BARROS RODRIGUES'	),
(	3880877	,	'brenda-ruviaro@defensoria.rs.gov.br'	,	'BRENDA ALBINE SARTORI RUVIARO'	),
(	3880885	,	'amanda-gonçalves@defensoria.rs.gov.br'	,	'AMANDA REIS GONÇALVES'	),
(	3880907	,	'marcelo-merlo@defensoria.rs.gov.br'	,	'MARCELO MERLO FLORES'	),
(	3880923	,	'diego-fogaça@defensoria.rs.gov.br'	,	'DIEGO FERNANDO FOGAÇA TEIXEIRA'	),
(	3880931	,	'cristiana-vitoria@defensoria.rs.gov.br'	,	'CRISTIANA DA SILVA VITÓRIA'	),
(	3880958	,	'aline-oliveira@defensoria.rs.gov.br'	,	'ALINE CERUTTI DE OLIVEIRA'	),
(	3880974	,	'otavio-otilia@defensoria.rs.gov.br'	,	'OTÁVIO DE VARGAS OTILIA'	),
(	3881024	,	'antonio-fontoura@defensoria.rs.gov.br'	,	'ANTÔNIO CARRÉ DA FONTOURA'	),
(	3881059	,	'manoela-querino@defensoria.rs.gov.br'	,	'MANOELA ANTUNES SITKO QUERINO'	),
(	3881210	,	'jessica-antonio@defensoria.rs.gov.br'	,	'JÉSSICA DE SOUZA ANTONIO'	),
(	3881237	,	'guilermo-rocha@defensoria.rs.gov.br'	,	'GUILERMO TIMM ROCHA'	),
(	3895467	,	'bruna-oliveira@defensoria.rs.gov.br'	,	'BRUNA RODRIGUES DE OLVIEIRA'	),
(	3895475	,	'janaina-razzera@defensoria.rs.gov.br'	,	'JANAINA NUNES RAZZERA'	),
(	3895491	,	'julia-sanches@defensoria.rs.gov.br'	,	'JULIA JURE DA SILVA SANCHES'	),
(	3895521	,	'ana-dauve@defensoria.rs.gov.br'	,	'ANA CAROLINA DAUVE'	),
(	3895530	,	'andre-batista@defensoria.rs.gov.br'	,	'ANDRE LUIS LUCERO BATISTA'	),
(	3895548	,	'anne-favero@defensoria.rs.gov.br'	,	'ANNE BEATRIZ FAVERO'	),
(	3895556	,	'benhur-laurentino@defensoria.rs.gov.br'	,	'BENHUR SALINI LAURENTINO'	),
(	3895572	,	'bruna-silva@defensoria.rs.gov.br'	,	'BRUNA CASALI DA SILVA'	),
(	3895580	,	'bruno-heis@defensoria.rs.gov.br'	,	'BRUNO DALPIAN HEIS'	),
(	3895610	,	'celia-poa@yahoo.com.br'	,	'CÉLIA MURUSSI SILVEIRA'	),
(	3895661	,	'douglas-santos@defensoria.rs.gov.br'	,	'DOUGLAS EVANDRO SANTOS'	),
(	3895688	,	'fernanda-alves@defensoria.rs.gov.br'	,	'FERNANDA DIAS ALVES'	),
(	3895696	,	'fernanda-silva@defensoria.rs.gov.br'	,	'FERNANDA TEDESCO SILVA'	),
(	3895718	,	'cassia-dias@defensoria.rs.gov.br'	,	'CASSIA LOPES DA SILVEIRA DIAS'	),
(	3895734	,	'gessica-camara@defensoria.rs.gov.br'	,	'GESSICA PACHECO CAMARA'	),
(	3895793	,	'joel-oliveira@defensoria.gov.rs'	,	'JOEL MÓISES DE OLIVEIRA'	),
(	3895858	,	'lorena-souza@defensoria.rs.gov.br'	,	'LORENA PINTO DE SOUZA'	),
(	3895866	,	'denise-stohlirck@defensoria.rs.gov.br'	,	'DENISE STOHLIRCK'	),
(	3895882	,	'luana-castro@defensoria.rs.gov.br'	,	'LUANA CHAGAS CASTRO'	),
(	3895904	,	'luciano-destro@defensoria.rs.gov.br'	,	'LUCIANO SESTI DESTRO'	),
(	3895920	,	'lucien-pires@defensoria.rs.gov.br'	,	'LUCIEN CARLOS SILVEIRA PIRES'	),
(	3895998	,	'maria-costa@defensoria.rs.gov.br'	,	'MARIA LUIZA DA COSTA'	),
(	3896021	,	'alessandra-pereira@defensoria.rs.gov.br'	,	'ALESSANDRA DOS SANTOS PEREIRA'	),
(	3896030	,	'natasha-bard@defensoria.rs.gov.br'	,	'NATASHA LIS STREIT BARD'	),
(	3896048	,	'maximiliano-kegler@defensoria.rs.gov.br'	,	'MAXIMILIANO BORDIM KEGLER'	),
(	3896099	,	'priscila-pinto@defensoria.rs.gov.br'	,	'PRISCILA ROUSANI PINTO'	),
(	3896102	,	'daniel-caye@defensoria.rs.gov.br'	,	'DANIEL PAULO CAYE'	),
(	3896110	,	'renata-mussi@defensoria.rs.gov.br'	,	'RENATA LUIZ MUSSI'	),
(	3896129	,	'tais-coimbra@defensoria.rs.gov.br'	,	'TAYLA MACHADO CARVALHO'	),
(	3896137	,	'rosane-breier@defensoria.rs.gov.br'	,	'ROSANE PORTO BREIER'	),
(	3896153	,	'tafate-dias@defensoria.rs.gov.br'	,	'TAFATE VIANA DIAS VILELA'	),
(	3896188	,	'carla-comette@defensoria.rs.gov.br'	,	'CARLA COMETTE'	),
(	3896196	,	'vania-pazdiora@defensoria.rs.gov.br'	,	'VÂNIA CARLA PAZDIORA'	),
(	3896200	,	'tais-coimbra@defensoria.rs.gov.br'	,	'TAIS VASCONCELOS COIMBRA'	),
(	3896218	,	'vinicius-carvalho@defensoria.rs.gov.br'	,	'VINICIUS DOS SANTOS CARVALHO'	),
(	3896234	,	'talita-flores@defensoria.rs.gov.br'	,	'TALITA BOTEGA FLORES'	),
(	3896250	,	'marilia-almeida@defensoria.rs.gov.br'	,	'MARILIA CASANOVA DE ALMEIDA'	),
(	3896323	,	'juliano-maffazioli@defensoria.rs.gov.br'	,	'JULIANO DE NARDO MAFFAZIOLI'	),
(	3896374	,	'lauren-muller@defensoria.rs.gov.br'	,	'LAUREN WILLERS MULLER'	),
(	3896455	,	'AROLDOVIECILI@YAHOO.COM.BR'	,	'AROLDO VIECILI'	),
(	3896463	,	'rosane-correa@defensoria.rs.gov.br'	,	'ROSANE DA ROSA CORREA'	),
(	3896536	,	'lucas-brito@defensoria.rs.gov.br'	,	'LUCIANA DULLIUS FRAGA'	),
(	3896676	,	'deniselli-feltrin@defensoria.rs.gov.br'	,	'DENISELLI LOPES AYRES FELTRIN'	),
(	3903141	,	'patrick-alves@defensoria.rs.gov.br'	,	'PATRICK LIMA FERNANDES ALVES'	),
(	3920887	,	'stephanie-serafini@defensoria.rs.gov.br'	,	'STEPHANIE VILELA SERAFINI'	),
(	3920984	,	'telma-fraga@defensoria.rs.gov.br'	,	'TELMA CORREA DE FRAGA'	),
(	3921131	,	'thamyz-peres@defensoria.rs.gov.br'	,	'THAMYZ BRITO PERES'	),
(	3921212	,	'thierre-veiga@defensoria.rs.gov.br'	,	'THIERRE MIRANDA DA VEIGA'	),
(	3921387	,	'vander-madrid@defensoria.rs.gov.br'	,	'VÂNDER LUIS DA SILVA MADRID'	),
(	3921840	,	'luiza-christmann@defensoria.rs.gov.br'	,	'LUIZA CHRISTMANN'	),
(	3921948	,	'jeferson-bertolo@defensoria.rs.gov.br'	,	'JEFERSON LUIZ BERTOLO'	),
(	3922120	,	'ananda-longo@defensoria.rs.gov.br'	,	'ANANDA LONGO'	),
(	3922162	,	'anderson-schorr@defensoria.rs.gov.br'	,	'ANDERSON LUIZ MATTOS SCHORR'	),
(	3922200	,	'arnaldo-neto@defensoria.rs.gov.br'	,	'ARNALDO ALVES PEREIRA NETO'	),
(	3925099	,	'everton-bartz@defensoria.rs.gov.br'	,	'EVERTON FRANCIS PEREIRA MADRUGA BARTZ'	),
(	3925307	,	'carolina-campos@defensoria.rs.gov.br'	,	'CAROLINA SILVA COSTA ILHEU CAMPOS'	),
(	3925447	,	'caroline-cardoso@defensoria.rs.gov.br'	,	'CAROLINE MARQUES CARDOSO'	),
(	3925544	,	'clareana-ferreira@defensoria.rs.gov.br'	,	'CLAREANA KUNZLER FERREIRA'	),
(	3925609	,	'emely-lubschinski@defensoria.rs.gov.br'	,	'EMELY LUBSCHINSKI'	),
(	3925811	,	'humberto-ribeiro@defensoria.rs.gov.br'	,	'HUMBERTO BORGES RIBEIRO'	),
(	3926141	,	'mariana-buckowski@defensoria.rs.gov'	,	'MARIANA BUCKOWSKI'	),
(	3926206	,	'paulo-silva@defensoria.rs.gov.br'	,	'PAULO JEFFERSON SOUSA DA SILVA'	),
(	3926290	,	'suelen-canal@defensoria.rs.gov.br'	,	'SUELEN CANAL'	),
(	3950506	,	'solange-rydz@defensoria.rs.gov.br'	,	'SOLANGE GOMES DA SILVA RYDZ'	),
(	3964434	,	'gilcea-silva@defensoria.rs.gov.br'	,	'GILCÉA DA GLÓRIA SILVA'	),
(	3964450	,	'marcela-andreata@defensoria.rs.gov.br'	,	'MARCELA VALADARES GONTIJO ANDREATA'	),
(	3964523	,	'huberto-timm@defensoria.rs.gov.br'	,	'HUBERTO MATHIAS TIMM'	),
(	3965112	,	'cristiano-pegorini@defensoria.rs.gov.br'	,	'CRISTIANO DE AZEREDO PEGORINI'	),
(	3965155	,	'anelise-cornelio@defensoria.rs.gov.br'	,	'ANELISE FONTANA CORNELIO'	),
(	3965333	,	'mariany-machado@defensoria.rs.gov.br'	,	'MARIANY HAYGERT MACHADO'	),
(	3965392	,	'mauricio-correa@defensoria.rs.gov.br'	,	'MAURÍCIO MENDES CORRÊA'	),
(	3965414	,	'nathalie-ferreira@defensoria.rs.gov.br'	,	'NATHALIE GUT FERREIRA'	),
(	3965422	,	'paulo-rodrigues@defensoria.rs.gov.br'	,	'PAULO RICARDO DE MOURA RODRIGUES'	),
(	3965635	,	'catiane-norbert@defensoria.rs.gov.br'	,	'CATIANE TEIXEIRA REIS NORBERT'	),
(	3965643	,	'diego-nascimento@defensoria.rs.gov.br'	,	'DIEGO NASCIMENTO DA SILVA'	),
(	3965660	,	'fabiane-russi@defensoria.rs.gov.br'	,	'FABIANE GARCIA RUSSI'	),
(	3965708	,	'felipe-wild@defensoria.rs.gov.br'	,	'FELIPE WILD'	),
(	3965716	,	'grace-villanova@defensoria.rs.gov.br'	,	'GRACE VIVIANE FRIGO VILLA NOVA'	),
(	3965759	,	'rafaela-moraes@defensoria.rs.gov.br'	,	'RAFAELA SANTIAGO MORAES'	),
(	3965856	,	'sissi-holderried@defensoria.rs.gov.br'	,	'SISSI HOLDERRIED'	),
(	3965872	,	'karen-berton@deefnsoria.rs.gov.br'	,	'KAREN ROCHA DA ROSA BERTON'	),
(	3965899	,	'cristopher-vidor@defensoria.rs.gov.br'	,	'CRISTOPHER ALEXANDER MARTINS VIDOR'	),
(	3965970	,	'julio-souza@defensoria.rs.gov.br'	,	'JULIO ODRACIR OLIVEIRA DE SOUZA'	),
(	3966046	,	'daniel-boeira@defensoria.rs.gov.br'	,	'DANIEL DE OLIVEIRA BOEIRA'	),
(	3966089	,	'rafael-munsberg@defensoria.rs.gov.br'	,	'RAFAEL BECKER STEFFEN MUNSBERG'	),
(	3966410	,	'carlos-monteiro@defensoria.rs.gov.br'	,	'CARLOS MAURÍCIO MONTEIRO'	),
(	3966658	,	'valeria-sisson@defensoria.rs.gov.br'	,	'VALÉRIA ZANARDO SISSON'	),
(	3966895	,	'marcelo-lopes@defensoria.rs.gov.br'	,	'MARCELO GONÇALVES LOPES'	),
(	3967182	,	'luiz-santos@defensoria.rs.gov.br'	,	'LUIZ DARCI MARTINS DOS SANTOS'	),
(	3967387	,	'bruno-hahn@defensoria.rs.gov.br'	,	'BRUNO BOFF HAHN'	),
(	3967409	,	'claudia-bergamin@defensoria.rs.gov.br'	,	'CLÁUDIA REGINA GALINA BERGAMIN'	),
(	3967433	,	'luiz-lorenci@defensoria.rs.gov.br'	,	'LUIZ FERNANDO LORENCI'	),
(	3968200	,	'marjorie-teixeira@defensoria.rs.gov.br'	,	'MARJORIE FÁTIMA BECK TEIXEIRA'	),
(	3968243	,	'andrea-born@dpe.rs.gov.br'	,	'ANDRÉA STORCH BORN'	),
(	4208072	,	'ada-rodrigues@defensoria.rs.gov.br'	,	'ADA SATHLER  RODRIGUES'	),
(	4208153	,	'rodrigo-remonti@defensoria.rs.gov.br'	,	'RODRIGO AUATT PAES REMONTI'	),
(	4208161	,	'sandra-marroni@defensoria.rs.gov.br'	,	'SANDRA MARILISE WENTZ MARRONI'	),
(	4208358	,	'catarina-rohr@defensoria.rs.gov.br'	,	'CATARINA ROHR'	),
(	4208382	,	'eder-yabel@defensoria.rs.gov.br'	,	'ÉDER JACKSON DOS SANTOS YABEL'	),
(	4208439	,	'eduardo-schreiber@defensoria.rs.gov.br'	,	'EDUARDO FONTES SCHREIBER'	),
(	4209125	,	'marilia-todeschini@defensoria.rs.gov.br'	,	'MARÍLIA LUÍSA ROZEC TODESCHINI'	),
(	4209141	,	'nadja-silva@defensoria.rs.gov.br'	,	'NADJA GONÇAVES DA SILVA'	),
(	4209150	,	'nelson-altmann@defensoria.rs.gov.br'	,	'NELSON FERNANDO ALTMANN'	),
(	4214838	,	'andre-silveira@defensoria.rs.gov.br'	,	'ANDRÉ DA SILVEIRA'	),
(	4214870	,	'camila-copetti@defensoria.rs.gov.br'	,	'CAMILA COPETTI'	),
(	4214897	,	'debora-rigon@defensoria.rs.gov.br'	,	'DÉBORA DA SILVA RIGON'	),
(	4214927	,	'felipe-silva@defensoria.rs.gov.br'	,	'FELIPE GALHARDO BARBOSA SILVA'	),
(	4214943	,	'fernanda-cerqueira@defensoria.rs.gov.br'	,	'FERNANDA SECCHI CERQUEIRA'	),
(	4214994	,	'neith-freire@defensoria.rs.gov.br'	,	'NEITH MARIA KROEFF BARBOSA FREIRE'	),
(	4215010	,	'patricia-vasconselos@defensoria.rs.gov.br'	,	'PATRÍCIA ALMEIDA VASCONSELOS'	),
(	4215044	,	'vladmir-policena@defensoria.rs.gov.br'	,	'VLADMIR IÓRIO POLICENA'	),
(	4215249	,	'lisia-brasil@defensoria.rs.gov.br'	,	'LISIA DA SILVA BRASIL'	),
(	4215273	,	'juliana-melo@defensoria.rs.gov.br'	,	'JULIANA FREITAS DE MELO'	),
(	4222563	,	'ana-maciel@defensoria.rs.gov.br'	,	'ANA AMÉLIA MACIÉL'	),
(	4222580	,	'gabriel-regla@defensoria.rs.gov.br'	,	'GABRIEL REGLA'	),
(	4222598	,	'guilherme-goncalves@defensoria.rs.gov.br'	,	'GUILHERME OSTJEN GONÇALVES'	),
(	4222857	,	'maicon-martins@defensoria.rs.gov.br'	,	'MAICON CAMARGO MARTINS'	),
(	4227204	,	'luana-medeiros@defensoria.rs.gov.br'	,	'LUANA BERNARDINES MEDEIROS'	),
(	4228308	,	'esmael-fagundes@defensoria.rs.gov.br'	,	'ESMAEL PEREIRA FAGUNDES'	),
(	4228464	,	'suzana-lopes@defensoria.rs.gov.br'	,	'SUZANA LOPES'	),
(	4230680	,	'luciana-stein@defensoria.rs.gov.br'	,	'LUCIANA JUNGUES STEIN'	);

--SELECT '('
--      ,s.matricula
--      ,','
--      ,''''+o.email+''''
--      ,','
--      ,''''+o.NOME+''''
--      ,'),'
--  FROM [db_removal_tecnicos].[dbo].[tb_servidores] s
-- inner join [PUB].[dbo].[VIEWOLAPPESSOAL] o on (s.matricula = o.matricula)