insert into servidores (matricula, email_servidor, nome_completo) values (599000,'suzana-velo@dpe.rs.gov.br','SUZANA IARA DORA VELO');
insert into servidores (matricula, email_servidor, nome_completo) values (799831,'claudete-pereira@dpe.rs.gov.br','CLAUDETE CAPAVERDE PEREIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (813591,'luiz-schutz@dpe.rs.gov.br','LUIZ ALFREDO SCHUTZ');
insert into servidores (matricula, email_servidor, nome_completo) values (1053493,'yara-nasario@dpe.rs.gov.br','YARA NASARIO');
insert into servidores (matricula, email_servidor, nome_completo) values (1069012,'ivanise-deckmann@dpe.rs.gov.br','IVANISE MACIEL DECKMANN');
insert into servidores (matricula, email_servidor, nome_completo) values (1129830,'antonio-junior@dpe.rs.gov.br','ANTONIO CARLOS CAVALHEIRO JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (1196618,'cleusatrevisan@dpe.rs.gov.br','CLEUSA MARIA RIBEIRO TREVISAN');
insert into servidores (matricula, email_servidor, nome_completo) values (1201913,'fatima-moraes@dpe.rs.gov.br','FATIMA BEATRIZ HAAG DE MORAES');
insert into servidores (matricula, email_servidor, nome_completo) values (1227670,'andre-joao@dpe.rs.gov.br','ANDRE LIPP JOAO');
insert into servidores (matricula, email_servidor, nome_completo) values (1230069,'nilza-possebon@dpe.rs.gov.br','NILZA ANTUNES POSSEBON');
insert into servidores (matricula, email_servidor, nome_completo) values (1270702,'maria-almeida@dpe.rs.gov.br','MARIA DA GLORIA SCHILLING DE ALMEIDA');
insert into servidores (matricula, email_servidor, nome_completo) values (1293672,'rosangela-santos@dpe.rs.gov.br','ROSANGELA TEREZINHA GOULART DOS SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (1312014,'jussara-acosta@dpe.rs.gov.br','JUSSARA MARIA BARBOSA ACOSTA');
insert into servidores (matricula, email_servidor, nome_completo) values (1320408,'marni-zat@dpe.rs.gov.br','MARNI MARIA ZAT');
insert into servidores (matricula, email_servidor, nome_completo) values (1406779,'clorinda-silva@dpe.rs.gov.br','CLORINDA IZABEL GOMES DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (1406817,'ricardo-borba@dpe.rs.gov.br','RICARDO MARQUES BORBA');
insert into servidores (matricula, email_servidor, nome_completo) values (1406965,'maria-oliveira@dpe.rs.gov.br','MARIA ADRIANA MEDEIROS OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (1406973,'joao-kaufmann@dpe.rs.gov.br','JOAO RENATO KAUFMANN');
insert into servidores (matricula, email_servidor, nome_completo) values (1407023,'luiz-quintella@dpe.rs.gov.br','LUIZ ANTONIO AYRES GUEDES QUINTELLA');
insert into servidores (matricula, email_servidor, nome_completo) values (1408305,'marcia-netto@dpe.rs.gov.br','MARCIA MULLER NETTO');
insert into servidores (matricula, email_servidor, nome_completo) values (1408577,'rosangela-rodrigues@dpe.rs.gov.br','ROSANGELA DE TOLEDO RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (1408593,'isis-marques@dpe.rs.gov.br','ISIS AZEVEDO MARQUES');
insert into servidores (matricula, email_servidor, nome_completo) values (1408607,'adrianabarcellos@dpe.rs.gov.br','ADRIANA HERVE CHAVES BARCELLOS');
insert into servidores (matricula, email_servidor, nome_completo) values (1409808,'adriana-burger@dpe.rs.gov.br','ADRIANA FAGUNDES BURGER');
insert into servidores (matricula, email_servidor, nome_completo) values (1412329,'helena-grillo@dpe.rs.gov.br','HELENA MARIA PIRES GRILLO');
insert into servidores (matricula, email_servidor, nome_completo) values (1417908,'jose-andrade@dpe.rs.gov.br','JOSE FRANCISCO FERREIRA DE ANDRADE');
insert into servidores (matricula, email_servidor, nome_completo) values (1417916,'jussara-rocha@defensoria.rs.gov.br','JUSSARA TEREZA OSORIO DA ROCHA');
insert into servidores (matricula, email_servidor, nome_completo) values (1428403,'telmo-sandrini@dpe.rs.gov.br','TELMO MENDES SANDRINI');
insert into servidores (matricula, email_servidor, nome_completo) values (1431692,'sandra-silveira@dpe.rs.gov.br','SANDRA REGINA FALCETA DA SILVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (1471198,'viviane-agostini@dpe.rs.gov.br','VIVIANE AGOSTINI SILVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (1583433,'gilberto-tomelero@dpe.rs.gov.br','GILBERTO ERNESTO TOMELERO');
insert into servidores (matricula, email_servidor, nome_completo) values (1604317,'carlos-guimaraes@dpe.rs.gov.br','CARLOS ESCOBAR GUIMARAES');
insert into servidores (matricula, email_servidor, nome_completo) values (1606212,'cintialuzzatto@dpe.rs.gov.br','CINTIA LUZZATTO');
insert into servidores (matricula, email_servidor, nome_completo) values (1606964,'miguel-junior@dpe.rs.gov.br','MIGUEL SEADI JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (1637576,'sandro-silva@dpe.rs.gov.br','SANDRO SANTOS DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (1637835,'antonio-oliveira@dpe.rs.gov.br','ANTONIO FLAVIO DE OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (1637878,'claudiocovatti@dpe.rs.gov.br','CLAUDIO LUIZ COVATTI');
insert into servidores (matricula, email_servidor, nome_completo) values (1640267,'luciana-kern@dpe.rs.gov.br','LUCIANA PEREIRA KERN');
insert into servidores (matricula, email_servidor, nome_completo) values (1640526,'marcelo-silva@dpe.rs.gov.br','MARCELO DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (1648519,'aline-collet@dpe.rs.gov.br','ALINE CASPANI COLLET');
insert into servidores (matricula, email_servidor, nome_completo) values (1659421,'eledi-porto@dpe.rs.gov.br','ELEDI AMORIM PORTO');
insert into servidores (matricula, email_servidor, nome_completo) values (1674919,'marcelo-almeida@dpe.rs.gov.br','MARCELO TURELA DE ALMEIDA');
insert into servidores (matricula, email_servidor, nome_completo) values (1707060,'regis-xavier@dpe.rs.gov.br','REGIS AUGUSTO MARTINS XAVIER');
insert into servidores (matricula, email_servidor, nome_completo) values (1729519,'regina-borges@dpe.rs.gov.br','REGINA CELIA RIZZON BORGES DE MEDEIROS');
insert into servidores (matricula, email_servidor, nome_completo) values (1794280,'luciana-borges@dpe.rs.gov.br','LUCIANA SALVADOR BORGES');
insert into servidores (matricula, email_servidor, nome_completo) values (1795856,'hilton-vaz@dpe.rs.gov.br','HILTON ROGERIO FERREIRA VAZ');
insert into servidores (matricula, email_servidor, nome_completo) values (1866680,'clevenice-scopel@dpe.rs.gov.br','CLEVENICE SCOPEL');
insert into servidores (matricula, email_servidor, nome_completo) values (1879073,'greice-portal@dpe.rs.gov.br','GREICE GRAZZIOTIN PORTAL');
insert into servidores (matricula, email_servidor, nome_completo) values (1882481,'sidney-berger@dpe.rs.gov.br','SIDNEY BERGER');
insert into servidores (matricula, email_servidor, nome_completo) values (1902008,'villetti@defensoria.rs.gov.br','NELITO CELSO VILLETTI');
insert into servidores (matricula, email_servidor, nome_completo) values (2280256,'alexandre-rodrigues@dpe.rs.gov.br','ALEXANDRE BRANDAO RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (2391953,'andrey-melo@dpe.rs.gov.br','ANDREY REGIS DE MELO');
insert into servidores (matricula, email_servidor, nome_completo) values (2392585,'arlei-batistella@dpe.rs.gov.br','ARLEI ANTONIO BATISTELLA');
insert into servidores (matricula, email_servidor, nome_completo) values (2422018,'joao-paz@dpe.rs.gov.br','JOAO OTAVIO CARMONA PAZ');
insert into servidores (matricula, email_servidor, nome_completo) values (2438690,'silvia-brum@dpe.rs.gov.br','SILVIA PINHEIRO DE BRUM');
insert into servidores (matricula, email_servidor, nome_completo) values (2442760,'katerine-braun@defensoria.rs.gov.br','KATERINE OLMEDO BRAUN');
insert into servidores (matricula, email_servidor, nome_completo) values (2455510,'andrea-santo@dpe.rs.gov.br','ANDREA ROCHA DO ESPIRITO SANTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2494752,'doeli-arnt@dpe.rs.gov.br','SOELI DE ALVARENGA ARNT');
insert into servidores (matricula, email_servidor, nome_completo) values (2516071,'aline-lovatto@dpe.rs.gov.br','ALINE CORREA LOVATTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2516080,'antonio-filho@dpe.rs.gov.br','ANTONIO AUGUSTO KORSACK FILHO');
insert into servidores (matricula, email_servidor, nome_completo) values (2516098,'cristiaine-johann@dpe.rs.gov.br','CRISTIAINE ANGELITA JOHANN');
insert into servidores (matricula, email_servidor, nome_completo) values (2516101,'christine-balbinot@dpe.rs.gov.br','CHRISTINE BALBINOT');
insert into servidores (matricula, email_servidor, nome_completo) values (2516110,'elis-taffarel@dpe.rs.gov.br','ELIS REGINA TAFFAREL');
insert into servidores (matricula, email_servidor, nome_completo) values (2516128,'fernanda-milman@dpe.rs.gov.br','FERNANDA KNIJNIK MILMAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2516144,'lisia-tabajara@dpe.rs.gov.br','LISIA MOSTARDEIRO VELASCO TABAJARA');
insert into servidores (matricula, email_servidor, nome_completo) values (2516152,'marcelo-dadalt@defensoria.rs.gov.br','MARCELO DADALT');
insert into servidores (matricula, email_servidor, nome_completo) values (2516160,'mauricia-teixeira@dpe.rs.gov.br','MAURICIA BARBOSA TEIXEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2516179,'tito-torres@dpe.rs.gov.br','TITO JOSE RAMBO OSORIO TORRES');
insert into servidores (matricula, email_servidor, nome_completo) values (2516187,'vivian-rigo@dpe.rs.gov.br','VIVIAN RIGO');
insert into servidores (matricula, email_servidor, nome_completo) values (2516195,'deise-collet@dpe.rs.gov.br','DEISE CASPANI COLLET');
insert into servidores (matricula, email_servidor, nome_completo) values (2516209,'gabriela-rodrigues@dpe.rs.gov.br','GABRIELA DA SILVA RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (2516217,'simone-prestes@dpe.rs.gov.br','SIMONE IRAZOQUI PRESTES');
insert into servidores (matricula, email_servidor, nome_completo) values (2516942,'eleonora-caldeira@dpe.rs.gov.br','ELEONORA MASCARENHAS MENDONCA CALDEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2517744,'waldemar-junior@dpe.rs.gov.br','WALDEMAR MENCHIK JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (2522977,'fabio-nery@dpe.rs.gov.br','FABIO DA COSTA NERY');
insert into servidores (matricula, email_servidor, nome_completo) values (2524155,'varlem-obelar@dpe.rs.gov.br','VARLEM DOS SANTOS OBELAR');
insert into servidores (matricula, email_servidor, nome_completo) values (2524570,'daniela-hidalgo@defensoria.rs.gov.br','DANIELA BOITO MAURMANN HIDALGO');
insert into servidores (matricula, email_servidor, nome_completo) values (2538989,'paula-souza@dpe.rs.gov.br','PAULA PINTO DE SOUZA');
insert into servidores (matricula, email_servidor, nome_completo) values (2546159,'carlalopes@dpe.rs.gov.br','CARLA ROBERTA PAHIM LOPES');
insert into servidores (matricula, email_servidor, nome_completo) values (2546167,'felipe-lavarda@dpe.rs.gov.br','FELIPE FACIN LAVARDA');
insert into servidores (matricula, email_servidor, nome_completo) values (2560291,'patricia-alcantara@dpe.rs.gov.br','PATRICIA BACCHIERI DUARTE ALCANTARA');
insert into servidores (matricula, email_servidor, nome_completo) values (2608863,'fernanda-almeida@dpe.rs.gov.br','FERNANDA MILLER DA CUNHA ALMEIDA');
insert into servidores (matricula, email_servidor, nome_completo) values (2608987,'fernanda-moreira@dpe.rs.gov.br','FERNANDA DE SOUZA MOREIRA TORRES');
insert into servidores (matricula, email_servidor, nome_completo) values (2608995,'anilori-lazzaron@dpe.rs.gov.br','ANILORI LAZZARON');
insert into servidores (matricula, email_servidor, nome_completo) values (2609002,'sirlane-lazzeri@dpe.rs.gov.br','SIRLANE MARASCA LAZZERI');
insert into servidores (matricula, email_servidor, nome_completo) values (2612593,'rafaela-consalter@dpe.rs.gov.br','RAFAELA CONSALTER');
insert into servidores (matricula, email_servidor, nome_completo) values (2615967,'saulo-junior@dpe.rs.gov.br','SAULO BRUM LEAL JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (2616963,'angelita-maders@dpe.rs.gov.br','ANGELITA MARIA MADERS');
insert into servidores (matricula, email_servidor, nome_completo) values (2617587,'tatiana-boeira@dpe.rs.gov.br','TATIANA KOSBY BOEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2618290,'juliana-lavigne@dpe.rs.gov.br','JULIANA COELHO DE LAVIGNE');
insert into servidores (matricula, email_servidor, nome_completo) values (2618303,'andreag@dpe.rs.gov.br','ANDREA GUBERT');
insert into servidores (matricula, email_servidor, nome_completo) values (2618311,'barbara-sartori@dpe.rs.gov.br','BARBARA BERNARDES DE OLIVEIRA SARTORI');
insert into servidores (matricula, email_servidor, nome_completo) values (2618320,'bernardo-simoes@dpe.rs.gov.br','BERNARDO CARVALHO SIMOES');
insert into servidores (matricula, email_servidor, nome_completo) values (2618338,'cassandra-halpern@dpe.rs.gov.br','CASSANDRA SIBEMBERG HALPERN');
insert into servidores (matricula, email_servidor, nome_completo) values (2618346,'elisa-stoduto@dpe.rs.gov.br','ELISA DIAS DE CASTRO STODUTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2618370,'marcos-martins@dpe.rs.gov.br','MARCOS VINICIUS MARTINS');
insert into servidores (matricula, email_servidor, nome_completo) values (2618389,'paulo-carrard@dpe.rs.gov.br','PAULO ANDRE CARRARD');
insert into servidores (matricula, email_servidor, nome_completo) values (2618397,'cristiano-heerdt@dpe.rs.gov.br','CRISTIANO VIEIRA HEERDT');
insert into servidores (matricula, email_servidor, nome_completo) values (2618400,'felipe-alves@dpe.rs.gov.br','FELIPE DOSSIN ALVES');
insert into servidores (matricula, email_servidor, nome_completo) values (2618419,'josane-heerdt@dpe.rs.gov.br','JOSANE DE ALMEIDA HEERDT');
insert into servidores (matricula, email_servidor, nome_completo) values (2618427,'lidia-menegotto@defensoria.rs.gov.br','LIDIA AMALIA ROSSI MENEGOTTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2618435,'adriana-rodrigues@dpe.rs.gov.br','ADRIANA VALDEREZ BITSCK RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (2618443,'lisiane-alves@dpe.rs.gov.br','LISIANE DE CASSIA ZANETTE ALVES');
insert into servidores (matricula, email_servidor, nome_completo) values (2618451,'barbaralenzi@dpe.rs.gov.br','BARBARA LENZI');
insert into servidores (matricula, email_servidor, nome_completo) values (2618460,'alvaro-fernandes@defensoria.rs.gov.br','ALVARO ROBERTO ANTANAVICIUS FERNANDES');
insert into servidores (matricula, email_servidor, nome_completo) values (2618524,'neusa-albrecht@dpe.rs.gov.br','NEUSA MARIA ALBRECHT');
insert into servidores (matricula, email_servidor, nome_completo) values (2618575,'lisandro-wottrich@dpe.rs.gov.br','LISANDRO LUIS WOTTRICH');
insert into servidores (matricula, email_servidor, nome_completo) values (2618605,'jose-marks@dpe.rs.gov.br','JOSE SALVADOR CABRAL MARKS');
insert into servidores (matricula, email_servidor, nome_completo) values (2618613,'gustavo-souza@dpe.rs.gov.br','GUSTAVO BRUNET DE SOUZA');
insert into servidores (matricula, email_servidor, nome_completo) values (2619148,'daniel-bittencourt@defensoria.rs.gov.br','DANIEL DE ARAUJO BITTENCOURT');
insert into servidores (matricula, email_servidor, nome_completo) values (2619156,'bruno-gil@dpe.rs.gov.br','BRUNO MIGUEL GIL');
insert into servidores (matricula, email_servidor, nome_completo) values (2620499,'janaina-oliveira@dpe.rs.gov.br','JANAINA RODRIGUES OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2625202,'danusakray@dpe.rs.gov.br','DANUSA ANDREA KRAY');
insert into servidores (matricula, email_servidor, nome_completo) values (2644916,'patricia-alessio@dpe.rs.gov.br','PATRICIA KETTERMANN NUNES');
insert into servidores (matricula, email_servidor, nome_completo) values (2644940,'tatiana-diniz@dpe.rs.gov.br','TATIANA PHILOMENA DINIZ');
insert into servidores (matricula, email_servidor, nome_completo) values (2644959,'rodrigo-grecco@dpe.rs.gov.br','RODRIGO LUZ GRECCO');
insert into servidores (matricula, email_servidor, nome_completo) values (2644967,'alcindo-strelow@dpe.rs.gov.br','ALCINDO STRELOW');
insert into servidores (matricula, email_servidor, nome_completo) values (2644975,'nilton-maria@dpe.rs.gov.br','NILTON LEONEL ARNECKE MARIA');
insert into servidores (matricula, email_servidor, nome_completo) values (2644983,'liliane-geyer@defensoria.rs.gov.br','LILIANE PAZ DEBLE');
insert into servidores (matricula, email_servidor, nome_completo) values (2644991,'andre-girotto@defensoria.rs.gov.br','ANDRE CASTANHO GIROTTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2645009,'luciana-faria@dpe.rs.gov.br','LUCIANA GOMES DE FARIA');
insert into servidores (matricula, email_servidor, nome_completo) values (2645017,'luciane-grezzana@dpe.rs.gov.br','LUCIANE GREZZANA');
insert into servidores (matricula, email_servidor, nome_completo) values (2657473,'fabio-souza@dpe.rs.gov.br','FABIO LUIS MARIANI DE SOUZA');
insert into servidores (matricula, email_servidor, nome_completo) values (2657490,'claudiabarros@dpe.rs.gov.br','CLAUDIA APARECIDA DE CAMARGO BARROS');
insert into servidores (matricula, email_servidor, nome_completo) values (2657520,'melissa-silveira@dpe.rs.gov.br','MELISSA TORRES SILVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2665956,'jaderson-paluchowski@dpe.rs.gov.br','JADERSON PALUCHOWSKI');
insert into servidores (matricula, email_servidor, nome_completo) values (2668890,'cinara-fratton@dpe.rs.gov.br','CINARA FURIAN FRATTON');
insert into servidores (matricula, email_servidor, nome_completo) values (2676869,'melissa-ampessan@dpe.rs.gov.br','MELISSA AMPESSAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2689472,'janaina-diel@dpe.rs.gov.br','JANAINA NEULS DIEL');
insert into servidores (matricula, email_servidor, nome_completo) values (2696290,'rafael-raphaelli@dpe.rs.gov.br','RAFAEL RAPHAELLI');
insert into servidores (matricula, email_servidor, nome_completo) values (2723484,'cintia-pereira@dpe.rs.gov.br','CINTIA BARBOSA PEREIRA MISSEL');
insert into servidores (matricula, email_servidor, nome_completo) values (2723492,'jimenes-chimeli@dpe.rs.gov.br','JIMENES MARY ROSA DE ARAUJO CHIMELI');
insert into servidores (matricula, email_servidor, nome_completo) values (2723506,'larissa-prado@dpe.rs.gov.br','LARISSA PILAR PRADO');
insert into servidores (matricula, email_servidor, nome_completo) values (2723514,'lucianne-bortowski@dpe.rs.gov.br','LUCIANNE BARRETO BORTOWSKI');
insert into servidores (matricula, email_servidor, nome_completo) values (2723522,'lucinara-oltramari@dpe.rs.gov.br','LUCINARA JOSEFINA OLTRAMARI');
insert into servidores (matricula, email_servidor, nome_completo) values (2723530,'luis-barbosa@dpe.rs.gov.br','LUIS ANTONIO DE SOUSA BARBOSA');
insert into servidores (matricula, email_servidor, nome_completo) values (2723557,'marta-zanchi@dpe.rs.gov.br','MARTA BEATRIZ TEDESCO ZANCHI');
insert into servidores (matricula, email_servidor, nome_completo) values (2724529,'egylene-chiarello@dpe.rs.gov.br','EGYLENE CHIARELLO');
insert into servidores (matricula, email_servidor, nome_completo) values (2724863,'fernanda-tome@defensoria.rs.gov.br','FERNANDA TEREZINHA TOME VIEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2724871,'cassio-fernandez@dpe.rs.gov.br','CASSIO MACHADO BITTENCOURT FERNANDEZ');
insert into servidores (matricula, email_servidor, nome_completo) values (2724880,'enir-avila@dpe.rs.gov.br','ENIR MADRUGA DE AVILA');
insert into servidores (matricula, email_servidor, nome_completo) values (2724898,'arianne-ranquetat@dpe.rs.gov.br','ARIANNE FISCHER RANQUETAT');
insert into servidores (matricula, email_servidor, nome_completo) values (2725649,'sabrina-nassif@dpe.rs.gov.br','SABRINA HOFMEISTER NASSIF');
insert into servidores (matricula, email_servidor, nome_completo) values (2725657,'luciane-trindade@dpe.rs.gov.br','LUCIANE MARTIN NAVARRINA TRINDADE');
insert into servidores (matricula, email_servidor, nome_completo) values (2729210,'valeria-brondani@dpe.rs.gov.br','VALERIA TABARELLI BRONDANI');
insert into servidores (matricula, email_servidor, nome_completo) values (2741580,'patricia-pagnussatt@dpe.rs.gov.br','PATRICIA PITHAN PAGNUSSATT FAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2741598,'cristiane-pretto@dpe.rs.gov.br','CRISTIANE PRETTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2745330,'kariny-faria@dpe.rs.gov.br','KARINY ROCHA GARCIA MASIERO FARIA');
insert into servidores (matricula, email_servidor, nome_completo) values (2746158,'fernando-scheffel@dpe.rs.gov.br','FERNANDO RUCKERT SCHEFFEL');
insert into servidores (matricula, email_servidor, nome_completo) values (2763974,'antonio-brum@dpe.rs.gov.br','ANTONIO MARCOS WENTZ BRUM');
insert into servidores (matricula, email_servidor, nome_completo) values (2763982,'patricia-buzatto@dpe.rs.gov.br','PATRICIA CONDE BUZATTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2774275,'rafael-carrard@dpe.rs.gov.br','RAFAEL CARRARD');
insert into servidores (matricula, email_servidor, nome_completo) values (2776014,'joao-moura@dpe.rs.gov.br','JOAO BATISTA OLIVEIRA DE MOURA');
insert into servidores (matricula, email_servidor, nome_completo) values (2787520,'tiago-santos@dpe.rs.gov.br','TIAGO RODRIGO DOS SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (2791870,'jose-teixeira@dpe.rs.gov.br','JOSE PATRICIO DOS SANTOS TEIXEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2791889,'eduardo-pedroso@dpe.rs.gov.br','EDUARDO FOSCARIN PEDROSO');
insert into servidores (matricula, email_servidor, nome_completo) values (2791897,'ana-pozzan@dpe.rs.gov.br','ANA PAULA POZZAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2791900,'luciana-guerra@dpe.rs.gov.br','LUCIANA ZUHEIR BADRA GUERRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2791927,'fernandamarins@dpe.rs.gov.br','FERNANDA BARBOSA MARINS');
insert into servidores (matricula, email_servidor, nome_completo) values (2791935,'eduardo-rodrigues@dpe.rs.gov.br','EDUARDO MARENGO RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (2791943,'alessandro-lema@dpe.rs.gov.br','ALESSANDRO GENARO SOARES LEMA');
insert into servidores (matricula, email_servidor, nome_completo) values (2814269,'alisson-romani@dpe.rs.gov.br','ALISSON DE LARA ROMANI');
insert into servidores (matricula, email_servidor, nome_completo) values (2833948,'igor-quevedo@dpe.rs.gov.br','IGOR RODRIGUES QUEVEDO');
insert into servidores (matricula, email_servidor, nome_completo) values (2868113,'karen@dpe.rs.gov.br','KAREN CARVALHO');
insert into servidores (matricula, email_servidor, nome_completo) values (2888890,'marisangela-minuzzi@dpe.rs.gov.br','MARISANGELA MINUZZI MELLO');
insert into servidores (matricula, email_servidor, nome_completo) values (2906570,'manuela-peixoto@defensoria.rs.gov.br','MANUELA BALSINI PEIXOTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2906597,'naira-sanches@dpe.rs.gov.br','NAIRA REGINA STEFANI SANCHES');
insert into servidores (matricula, email_servidor, nome_completo) values (2906643,'rogerio-bressan@defensoria.rs.gov.br','ROGERIO BRESSAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2906708,'denise-porto@dpe.rs.gov.br','DENISE ROCHA PORTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2906848,'alessandra-cruz@dpe.rs.gov.br','ALESSANDRA QUINES CRUZ');
insert into servidores (matricula, email_servidor, nome_completo) values (2912783,'irvan-filho@dpe.rs.gov.br','IRVAN ANTUNES VIEIRA FILHO');
insert into servidores (matricula, email_servidor, nome_completo) values (2912791,'antonio-ribeiro@dpe.rs.gov.br','ANTONIO AUGUSTO PACHECO RIBEIRO');
insert into servidores (matricula, email_servidor, nome_completo) values (2912805,'tomas-buchaim@dpe.rs.gov.br','TOMAS SALOTTI BUCHAIM');
insert into servidores (matricula, email_servidor, nome_completo) values (2912813,'marcela-goncalves@dpe.rs.gov.br','MARCELA FERNANDEZ GONCALVES BRESSANI');
insert into servidores (matricula, email_servidor, nome_completo) values (2912821,'ana-riatto@dpe.rs.gov.br','ANA PAULA DAL IGNA');
insert into servidores (matricula, email_servidor, nome_completo) values (2912830,'liseane-hartmann@dpe.rs.gov.br','LISEANE HARTMANN');
insert into servidores (matricula, email_servidor, nome_completo) values (2912880,'samara-wilhelm@defensoria.rs.gov.br','SAMARA WILHELM HEERDT');
insert into servidores (matricula, email_servidor, nome_completo) values (2912899,'mariana-muniz@dpe.rs.gov.br','MARIANA PY MUNIZ CAPPELLARI');
insert into servidores (matricula, email_servidor, nome_completo) values (2912937,'estevam-silva@dpe.rs.gov.br','ESTEVAM KRIEGER BENTO DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (2913089,'ana-ponte@dpe.rs.gov.br','ANA CARINA TEIXEIRA DAL PONTE');
insert into servidores (matricula, email_servidor, nome_completo) values (2927705,'rodrigo-noschang@dpe.rs.gov.br','RODRIGO NOSCHANG');
insert into servidores (matricula, email_servidor, nome_completo) values (2938146,'adriana-nascimento@dpe.rs.gov.br','ADRIANA DE OLIVEIRA SCHEFER DO NASCIMENTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2940345,'cristine-monteiro@dpe.rs.gov.br','CRISTINE DAL MAGRO MONTEIRO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942437,'paula-oliveira@dpe.rs.gov.br','PAULA SIMOES DUTRA DE OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942445,'rafael-fonseca@dpe.rs.gov.br','RAFAEL BETTIO DA FONSECA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942461,'ricardo-sano@dpe.rs.gov.br','RICARDO SANO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942488,'robertascaf@dpe.rs.gov.br','ROBERTA SCAF SILVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942496,'rodolfo-malhao@dpe.rs.gov.br','RODOLFO LOREA MALHAO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942500,'rogerio-couto@dpe.rs.gov.br','ROGERIO SOUZA COUTO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942526,'taciana-carlos@dpe.rs.gov.br','TACIANA ESSER CARLOS KEHRVALD');
insert into servidores (matricula, email_servidor, nome_completo) values (2942534,'vitor-langaro@dpe.rs.gov.br','VITOR HUGO ZAPANI LANGARO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942577,'anelise-sturm@dpe.rs.gov.br','ANELISE CALIERON STURM');
insert into servidores (matricula, email_servidor, nome_completo) values (2942615,'angelo-trevisan@dpe.rs.gov.br','ANGELO TURRA TREVISAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2942623,'arianefreitas@dpe.rs.gov.br','ARIANE RAMOS DA CUNHA FREITAS RITTER');
insert into servidores (matricula, email_servidor, nome_completo) values (2942631,'carolinaetzberger@dpe.rs.gov.br','CAROLINA ETZBERGER');
insert into servidores (matricula, email_servidor, nome_completo) values (2942640,'daniela-bortolan@dpe.rs.gov.br','DANIELA WILDE BORTOLAN');
insert into servidores (matricula, email_servidor, nome_completo) values (2942658,'danusac@defensoria.rs.gov.br','DANUSA ANTONIA CECCATO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942666,'deboratorres@dpe.rs.gov.br','DEBORA DE OLIVEIRA DIAS TORRES');
insert into servidores (matricula, email_servidor, nome_completo) values (2942674,'dmazzarino@dpe.rs.gov.br','DIEGO LEANDRO MAZZARINO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942682,'elizandro-todeschini@dpe.rs.gov.br','ELIZANDRO TODESCHINI');
insert into servidores (matricula, email_servidor, nome_completo) values (2942704,'larissa-silveira@dpe.rs.gov.br','LARISSA PEDROLO SILVEIRA DOURADO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942712,'larissa-ferreira@dpe.rs.gov.br','LARISSA ROCHA FERREIRA CAON');
insert into servidores (matricula, email_servidor, nome_completo) values (2942720,'leonardo-darde@dpe.rs.gov.br','LEONARDO MARCELO DA SILVA DARDE');
insert into servidores (matricula, email_servidor, nome_completo) values (2942739,'lucas-pereira@dpe.rs.gov.br','LUCAS LESSA DE PEIXOTO PEREIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942755,'ernani-pupo@dpe.rs.gov.br','ERNANI RIBOLDI DAL PUPO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942763,'fabiana-morsch@dpe.rs.gov.br','FABIANA ALVES MORSCH');
insert into servidores (matricula, email_servidor, nome_completo) values (2942771,'fabiane-lontra@dpe.rs.gov.br','FABIANE RUPERTI LONTRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942780,'fernanda-fogazzi@dpe.rs.gov.br','FERNANDA PRETTO FOGAZZI SANCHOTENE');
insert into servidores (matricula, email_servidor, nome_completo) values (2942798,'gabriela-vaz@dpe.rs.gov.br','GABRIELA PRZYBYSZ VAZ');
insert into servidores (matricula, email_servidor, nome_completo) values (2942810,'igor-silva@dpe.rs.gov.br','IGOR MENINI DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942828,'jamile-nehme@dpe.rs.gov.br','JAMILE RODRIGUES NEHME DE TOLEDO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942836,'jonas-farenzena@dpe.rs.gov.br','JONAS SCAIN FARENZENA');
insert into servidores (matricula, email_servidor, nome_completo) values (2942844,'marcelo-candiago@dpe.rs.gov.br','MARCELO CANDIAGO');
insert into servidores (matricula, email_servidor, nome_completo) values (2942879,'milena-lisowski@dpe.rs.gov.br','MILENA ROCHA LISOWSKI DIPP');
insert into servidores (matricula, email_servidor, nome_completo) values (2942887,'miriane-tagliari@dpe.rs.gov.br','MIRIANE TAGLIARI');
insert into servidores (matricula, email_servidor, nome_completo) values (2945576,'roberta-silveira@dpe.rs.gov.br','ROBERTA DA SILVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2954567,'jucelito-villetti@defensoria.rs.gov.br','JUCELITO ANDRE VILLETTI');
insert into servidores (matricula, email_servidor, nome_completo) values (2983125,'ricardo-girardello@defensoria.rs.gov.br','RICARDO GIRARDELLO');
insert into servidores (matricula, email_servidor, nome_completo) values (2983141,'michelle-caputi@dpe.rs.gov.br','MICHELLE SALVANY CAPUTI');
insert into servidores (matricula, email_servidor, nome_completo) values (2983249,'tamara-agostini@dpe.rs.gov.br','TAMARA FLORES AGOSTINI');
insert into servidores (matricula, email_servidor, nome_completo) values (2983303,'carlaribeiro@dpe.rs.gov.br','CARLA CRISTIANE RIBEIRO CASSOL');
insert into servidores (matricula, email_servidor, nome_completo) values (2983370,'lia-balle@dpe.rs.gov.br','LIA SANTROVITSCH BALLE');
insert into servidores (matricula, email_servidor, nome_completo) values (2983397,'eugenio-junior@dpe.rs.gov.br','EUGENIO PEDRO GOMES DE OLIVEIRA JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (2997320,'grazziane-tonel@dpe.rs.gov.br','GRAZZIANE TONEL');
insert into servidores (matricula, email_servidor, nome_completo) values (2997355,'laura-veitenheimer@dpe.rs.gov.br','LAURA DE FERREIRA VEITENHEIMER');
insert into servidores (matricula, email_servidor, nome_completo) values (2997363,'camila-ferrareze@dpe.rs.gov.br','CAMILA FERRAREZE');
insert into servidores (matricula, email_servidor, nome_completo) values (2997371,'adriana-quadros@dpe.rs.gov.br','ADRIANA MUNHOZ DE QUADROS');
insert into servidores (matricula, email_servidor, nome_completo) values (2997380,'danielaoliveira@dpe.rs.gov.br','DANIELA OLIVEIRA BUENO');
insert into servidores (matricula, email_servidor, nome_completo) values (2997398,'marcelo-mosena@dpe.rs.gov.br','MARCELO MOSENA');
insert into servidores (matricula, email_servidor, nome_completo) values (2997401,'luciana-amin@dpe.rs.gov.br','LUCIANA RIBEIRO AMIN');
insert into servidores (matricula, email_servidor, nome_completo) values (2997410,'bibiana-santo@dpe.rs.gov.br','BIBIANA ASCARI DO ESPIRITO SANTO BENTO DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (2997428,'melina-coronel@dpe.rs.gov.br','MELINA PAIVA CORONEL');
insert into servidores (matricula, email_servidor, nome_completo) values (2997444,'andreia-rodrigues@dpe.rs.gov.br','ANDREIA PAZ RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (2997460,'felipe-kirchner@dpe.rs.gov.br','FELIPE KIRCHNER');
insert into servidores (matricula, email_servidor, nome_completo) values (2997479,'ana-bandeira@dpe.rs.gov.br','ANA MERCEDES MONDADORI BANDEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (2997487,'tiago-korbes@dpe.rs.gov.br','TIAGO KORBES');
insert into servidores (matricula, email_servidor, nome_completo) values (2997495,'andreia-rambo@dpe.rs.gov.br','ANDREIA RAMBO MORAES');
insert into servidores (matricula, email_servidor, nome_completo) values (3055400,'tatiana-silva@dpe.rs.gov.br','TATIANA CARVALHO AZAMBUJA DA SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (3065200,'morgana-gregori@dpe.rs.gov.br','MORGANA MAGALI GREGORI');
insert into servidores (matricula, email_servidor, nome_completo) values (3065219,'taisa-severico@dpe.rs.gov.br','TAISA SEVERICO');
insert into servidores (matricula, email_servidor, nome_completo) values (3065227,'ana-franke@dpe.rs.gov.br','ANA EMILIA FRANKE');
insert into servidores (matricula, email_servidor, nome_completo) values (3065235,'everton@dpe.rs.gov.br','EVERTON HERTZOG CASTILHOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3065243,'carolrodrigues@dpe.rs.gov.br','CAROLINE RIBEIRO RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (3065251,'caroline-panichi@dpe.rs.gov.br','CAROLINE LIMA E SILVA MAZZOLA PANICHI');
insert into servidores (matricula, email_servidor, nome_completo) values (3065260,'regina-bruchez@dpe.rs.gov.br','REGINA DOS SANTOS BRUCHEZ');
insert into servidores (matricula, email_servidor, nome_completo) values (3065278,'mauro-pereira@dpe.rs.gov.br','MAURO KAUFMANN PEREIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3065286,'sergio-junior@dpe.rs.gov.br','SERGIO DA SILVA FRAGA JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (3065294,'mateus-sanfelice@dpe.rs.gov.br','MATEUS MASSIA SANFELICE');
insert into servidores (matricula, email_servidor, nome_completo) values (3065308,'joziele-campana@dpe.rs.gov.br','JOZIELE BONA CAMPANA');
insert into servidores (matricula, email_servidor, nome_completo) values (3065316,'caroline-maisonnette@dpe.rs.gov.br','CAROLINE DELLA GIUSTINA MAISONNETTE');
insert into servidores (matricula, email_servidor, nome_completo) values (3087190,'ana-castro@dpe.rs.gov.br','ANA CAROLINA SAMPAIO PINHEIRO DE CASTRO');
insert into servidores (matricula, email_servidor, nome_completo) values (3090663,'daniela-schulz@dpe.rs.gov.br','DANIELA DE MORAIS SCHULZ');
insert into servidores (matricula, email_servidor, nome_completo) values (3090671,'danielaarend@dpe.rs.gov.br','DANIELA HASELEIN AREND');
insert into servidores (matricula, email_servidor, nome_completo) values (3090698,'paula-albuquerque@dpe.rs.gov.br','PAULA SCHWARTZMAN DE OLIVEIRA ALBUQUERQUE');
insert into servidores (matricula, email_servidor, nome_completo) values (3090710,'ingrid-lunardi@dpe.rs.gov.br','INGRID LERCH LUNARDI');
insert into servidores (matricula, email_servidor, nome_completo) values (3090728,'paula-granetto@dpe.rs.gov.br','PAULA BRITTO GRANETTO');
insert into servidores (matricula, email_servidor, nome_completo) values (3090736,'rafael-dourado@dpe.rs.gov.br','RAFAEL SILVEIRA DOURADO');
insert into servidores (matricula, email_servidor, nome_completo) values (3090752,'micaela-maso@dpe.rs.gov.br','MICAELA FALLEIRO DAL MASO DONADUSSI');
insert into servidores (matricula, email_servidor, nome_completo) values (3090760,'marcelle-boeckel@dpe.rs.gov.br','MARCELLE FERNANDES CARDOSO DE BOECKEL');
insert into servidores (matricula, email_servidor, nome_completo) values (3090779,'jose-medeiros@dpe.rs.gov.br','JOSE AUGUSTO DA COSTA MEDEIROS');
insert into servidores (matricula, email_servidor, nome_completo) values (3090787,'jviali@defensoria.rs.gov.br','JULIANO VIALI DOS SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3090809,'jaciara-ritter@dpe.rs.gov.br','JACIARA BARASUOL RITTER');
insert into servidores (matricula, email_servidor, nome_completo) values (3090817,'evandrolp@dpe.rs.gov.br','EVANDRO LUIS PITUCO');
insert into servidores (matricula, email_servidor, nome_completo) values (3131750,'aldo-junior@dpe.rs.gov.br','ALDO NERI DE VARGAS JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (3175901,'fabricio-souza@dpe.rs.gov.br','FABRICIO AZEVEDO DE SOUZA');
insert into servidores (matricula, email_servidor, nome_completo) values (3177041,'tarcizioperlin@dpe.rs.gov.br','TARCIZIO SCHERER PERLIN');
insert into servidores (matricula, email_servidor, nome_completo) values (3182304,'cristiana-olszewski@dpe.rs.gov.br','CRISTIANA KONRAD OLSZEWSKI');
insert into servidores (matricula, email_servidor, nome_completo) values (3182312,'gustavo-barbieri@dpe.rs.gov.br','GUSTAVO LINDENMEYER BARBIERI');
insert into servidores (matricula, email_servidor, nome_completo) values (3182320,'alvaro-magalhaes@dpe.rs.gov.br','ALVARO SIMOES MAGALHAES');
insert into servidores (matricula, email_servidor, nome_completo) values (3190013,'marcelia-favarin@dpe.rs.gov.br','MARCELIA COMINETTI FAVARIN');
insert into servidores (matricula, email_servidor, nome_completo) values (3197034,'gislaine-lima@dpe.rs.gov.br','GISLAINE BRUM DE LIMA');
insert into servidores (matricula, email_servidor, nome_completo) values (3201210,'alice-leon@defensoria.rs.gov.br','ALICE BACKES DE LEON');
insert into servidores (matricula, email_servidor, nome_completo) values (3201236,'eduardo-oliveira@dpe.rs.gov.br','EDUARDO BAPTISTA DE OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3201244,'marcia-so@dpe.rs.gov.br','MARCIA GUEDES SO');
insert into servidores (matricula, email_servidor, nome_completo) values (3201333,'dani-teles@dpe.rs.gov.br','DANI ACCORSI TELES');
insert into servidores (matricula, email_servidor, nome_completo) values (3201473,'cristiane-chitolina@dpe.rs.gov.br','CRISTIANE CHITOLINA FRIEDRICH');
insert into servidores (matricula, email_servidor, nome_completo) values (3209571,'rodrigopinho@dpe.rs.gov.br','RODRIGO GOMES PINHO');
insert into servidores (matricula, email_servidor, nome_completo) values (3233227,'robertapretto@dpe.rs.gov.br','ROBERTA DE LIMA PRETTO');
insert into servidores (matricula, email_servidor, nome_completo) values (3233367,'rafaelsusin@dpe.rs.gov.br','RAFAEL FERNANDO SUSIN');
insert into servidores (matricula, email_servidor, nome_completo) values (3378110,'lorainascotta@dpe.rs.gov.br','LORAINA RAQUEL SCOTTA');
insert into servidores (matricula, email_servidor, nome_completo) values (3378322,'raquelfellini@dpe.rs.gov.br','RAQUEL FELLINI');
insert into servidores (matricula, email_servidor, nome_completo) values (3378519,'emileneperin@dpe.rs.gov.br','EMILENE PERIN');
insert into servidores (matricula, email_servidor, nome_completo) values (3379493,'paulopinto@dpe.rs.gov.br','PAULO CESAR MARTINS PINTO');
insert into servidores (matricula, email_servidor, nome_completo) values (3382109,'renatosantos@dpe.rs.gov.br','RENATO MUNOZ DE OLIVEIRA SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3384624,'simonegobbo@dpe.rs.gov.br','SIMONE HUBNER CIOCCARI GOBBO');
insert into servidores (matricula, email_servidor, nome_completo) values (3385779,'henriquerosa@dpe.rs.gov.br','HENRIQUE MARDER DA ROSA');
insert into servidores (matricula, email_servidor, nome_completo) values (3386090,'fernandaperes@dpe.rs.gov.br','FERNANDA SANTOS PERES');
insert into servidores (matricula, email_servidor, nome_completo) values (3386406,'laonipoletto@defensoria.rs.gov.br','LAONI POLETTO');
insert into servidores (matricula, email_servidor, nome_completo) values (3389529,'deisisartori@dpe.rs.gov.br','DEISI SARTORI');
insert into servidores (matricula, email_servidor, nome_completo) values (3390594,'rafaelmachado@dpe.rs.gov.br','RAFAEL RODRIGUES DA SILVA PINHEIRO MACHADO');
insert into servidores (matricula, email_servidor, nome_completo) values (3390802,'carolinacervo@dpe.rs.gov.br','CAROLINA ZAGO CERVO');
insert into servidores (matricula, email_servidor, nome_completo) values (3394816,'gustavoluz@dpe.rs.gov.br','GUSTAVO DE OLIVEIRA DA LUZ');
insert into servidores (matricula, email_servidor, nome_completo) values (3395758,'fernandoschropfer@dpe.rs.gov.br','FERNANDO MOSCON SCHROPFER');
insert into servidores (matricula, email_servidor, nome_completo) values (3397408,'lauradias@dpe.rs.gov.br','LAURA SILVA DIAS');
insert into servidores (matricula, email_servidor, nome_completo) values (3400565,'mainapech@dpe.rs.gov.br','MAINA RIBEIRO PECH');
insert into servidores (matricula, email_servidor, nome_completo) values (3405737,'marcelooliveira@dpe.rs.gov.br','MARCELO BARTMANN OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3408302,'luizamartins@dpe.rs.gov.br','LUIZA DO CARMO MARTINS');
insert into servidores (matricula, email_servidor, nome_completo) values (3413039,'andressapaim@dpe.rs.gov.br','ANDRESSA RISSETTI PAIM');
insert into servidores (matricula, email_servidor, nome_completo) values (3413349,'monicazimmer@dpe.rs.gov.br','MONICA ZIMMER');
insert into servidores (matricula, email_servidor, nome_completo) values (3416500,'danielelima@dpe.rs.gov.br','DANIELE DA COSTA LIMA');
insert into servidores (matricula, email_servidor, nome_completo) values (3416950,'julianamariani@dpe.rs.gov.br','JULIANA VIEIRA MARIANI');
insert into servidores (matricula, email_servidor, nome_completo) values (3417050,'franciellebertani@dpe.rs.gov.br','FRANCIELLE BERTANI');
insert into servidores (matricula, email_servidor, nome_completo) values (3419126,'robertakappel@dpe.rs.gov.br','ROBERTA DIAS KAPPEL');
insert into servidores (matricula, email_servidor, nome_completo) values (3439208,'alexandrepiccoli@defensoria.rs.gov.br','ALEXANDRE PICCOLI');
insert into servidores (matricula, email_servidor, nome_completo) values (3439232,'julianoruschel@dpe.rs.gov.br','JULIANO RUSCHEL');
insert into servidores (matricula, email_servidor, nome_completo) values (3442454,'alinelatorre@dpe.rs.gov.br','ALINE RODRIGUES DE LATORRE');
insert into servidores (matricula, email_servidor, nome_completo) values (3444236,'gabrielseifriz@defensoria.rs.gov.br','GABRIEL LUIZ PINTO SEIFRIZ');
insert into servidores (matricula, email_servidor, nome_completo) values (3444635,'ricardogick@dpe.rs.gov.br','RICARDO DE AZAMBUJA GICK');
insert into servidores (matricula, email_servidor, nome_completo) values (3446263,'marciomaria@dpe.rs.gov.br','MARCIO LENINE ARNECKE MARIA');
insert into servidores (matricula, email_servidor, nome_completo) values (3446824,'lucianaschneider@dpe.rs.gov.br','LUCIANA ARTUS SCHNEIDER');
insert into servidores (matricula, email_servidor, nome_completo) values (3448835,'alinetelles@dpe.rs.gov.br','ALINE LOVATTO TELLES');
insert into servidores (matricula, email_servidor, nome_completo) values (3449688,'carlalizot@dpe.rs.gov.br','CARLA SCHOFFEL LIZOT');
insert into servidores (matricula, email_servidor, nome_completo) values (3449742,'danyzart@dpe.rs.gov.br','DANY MICHEL ZART');
insert into servidores (matricula, email_servidor, nome_completo) values (3449831,'patriciamuller@dpe.rs.gov.br','PATRICIA CASARIN MULLER');
insert into servidores (matricula, email_servidor, nome_completo) values (3450015,'lilianeoliveira@dpe.rs.gov.br','LILIANE BRAGA LUZ OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3493105,'carolinerodolfo@dpe.rs.gov.br','CAROLINE PICOLLI RODOLFO');
insert into servidores (matricula, email_servidor, nome_completo) values (3528537,'marcelopiton@dpe.rs.gov.br','MARCELO MARTINS PITON');
insert into servidores (matricula, email_servidor, nome_completo) values (3611701,'marianacesar@dpe.rs.gov.br','MARIANA MISSEL CESAR');
insert into servidores (matricula, email_servidor, nome_completo) values (3611817,'fernandawaick@dpe.rs.gov.br','FERNANDA AIME LAMP WAICK');
insert into servidores (matricula, email_servidor, nome_completo) values (3635635,'marilialokschin@dpe.rs.gov.br','MARILIA BROD LOKSCHIN');
insert into servidores (matricula, email_servidor, nome_completo) values (3635740,'clovisneto@dpe.rs.gov.br','CLOVIS ADAO PIZZAMIGLIO BOZZA NETO');
insert into servidores (matricula, email_servidor, nome_completo) values (3635767,'mariorheingantz@dpe.rs.gov.br','MARIO SILVEIRA ROSA RHEINGANTZ');
insert into servidores (matricula, email_servidor, nome_completo) values (3635775,'leticiabasso@dpe.rs.gov.br','LETICIA ANA BASSO');
insert into servidores (matricula, email_servidor, nome_completo) values (3635821,'raphaelcoelho@dpe.rs.gov.br','RAPHAEL VARELLA COELHO');
insert into servidores (matricula, email_servidor, nome_completo) values (3635830,'andreandrade@dpe.rs.gov.br','ANDRE ESTEVES DE ANDRADE');
insert into servidores (matricula, email_servidor, nome_completo) values (3635848,'raquelloy@defensoria.rs.gov.br','RAQUEL DORNELES LOY');
insert into servidores (matricula, email_servidor, nome_completo) values (3635856,'alinedalri@dpe.rs.gov.br','ALINE LANGNER DAL RI');
insert into servidores (matricula, email_servidor, nome_completo) values (3644138,'gustavoruffo@defensoria.rs.gov.br','GUSTAVO CATTELAN RUFFO');
insert into servidores (matricula, email_servidor, nome_completo) values (3644391,'ariongodoy@dpe.rs.gov.br','ARION ESCORSIN DE GODOY');
insert into servidores (matricula, email_servidor, nome_completo) values (3644464,'sergiomonteiro@dpe.rs.gov.br','SERGIO NODARI MONTEIRO');
insert into servidores (matricula, email_servidor, nome_completo) values (3644553,'wilianbolfoni@dpe.rs.gov.br','WILIAN GONCALVES BOLFONI');
insert into servidores (matricula, email_servidor, nome_completo) values (3644588,'leticiafurtado@defensoria.rs.gov.br','LETICIA PETER FURTADO');
insert into servidores (matricula, email_servidor, nome_completo) values (3644693,'andresilva@dpe.rs.gov.br','ANDRE AUGUSTO MAGALHAES SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (3644715,'domingoscosta@dpe.rs.gov.br','DOMINGOS BARROSO DA COSTA');
insert into servidores (matricula, email_servidor, nome_completo) values (3644723,'amandamariante@defensoria.rs.gov.br','AMANDA RAVANELLO MARIANTE');
insert into servidores (matricula, email_servidor, nome_completo) values (3649377,'julianaamaral@dpe.rs.gov.br','JULIANA JOBIM DO AMARAL');
insert into servidores (matricula, email_servidor, nome_completo) values (3657035,'dianacosta@dpe.rs.gov.br','DIANA RODRIGUES DA COSTA');
insert into servidores (matricula, email_servidor, nome_completo) values (3663701,'renanangeli@dpe.rs.gov.br','RENAN ANGELI');
insert into servidores (matricula, email_servidor, nome_completo) values (3663710,'mariliagabriela@dpe.rs.gov.br','MARILIA GABRIELA OLIVEIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3665755,'annaramos@dpe.rs.gov.br','ANNA CAROLINA MEIRA RAMOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3665810,'andreiagasparini@dpe.rs.gov.br','ANDREIA FILIANOTI GASPARINI');
insert into servidores (matricula, email_servidor, nome_completo) values (3665860,'brunocerejo@defensoria.rs.gov.br','BRUNO PUGIALLI CEREJO');
insert into servidores (matricula, email_servidor, nome_completo) values (3665950,'walterwillig@dpe.rs.gov.br','WALTER LUCHESE WILLIG');
insert into servidores (matricula, email_servidor, nome_completo) values (3665992,'leticianeves@dpe.rs.gov.br','LETICIA FERNANDES NEVES');
insert into servidores (matricula, email_servidor, nome_completo) values (3666026,'cristianobertuol@dpe.rs.gov.br','CRISTIANO BERTUOL');
insert into servidores (matricula, email_servidor, nome_completo) values (3666042,'barbarabrasil@dpe.rs.gov.br','BARBARA PALMEIRO BRASIL');
insert into servidores (matricula, email_servidor, nome_completo) values (3682099,'andreborges@dpe.rs.gov.br','ANDRE IGLESIAS E SILVA BORGES');
insert into servidores (matricula, email_servidor, nome_completo) values (3682161,'rodrigosimon@dpe.rs.gov.br','RODRIGO SIMON');
insert into servidores (matricula, email_servidor, nome_completo) values (3682277,'filipesilva@dpe.rs.gov.br','FILIPE MORAIS SILVA');
insert into servidores (matricula, email_servidor, nome_completo) values (3682315,'bibianaspode@dpe.rs.gov.br','BIBIANA SPODE');
insert into servidores (matricula, email_servidor, nome_completo) values (3682412,'joaomatias@dpe.rs.gov.br','JOAO TEIXEIRA GROSSI DE CASTRO MATIAS');
insert into servidores (matricula, email_servidor, nome_completo) values (3682471,'carolinalovato@dpe.rs.gov.br','CAROLINA VERCOZA LOVATO');
insert into servidores (matricula, email_servidor, nome_completo) values (3682528,'flaviasteinbruch@dpe.rs.gov.br','FLAVIA RUMI STEINBRUCH');
insert into servidores (matricula, email_servidor, nome_completo) values (3682595,'robertanozari@dpe.rs.gov.br','ROBERTA NOZARI');
insert into servidores (matricula, email_servidor, nome_completo) values (3682641,'camillahage@defensoria.rs.gov.br','CAMILLA SAFE MAIER HAGE');
insert into servidores (matricula, email_servidor, nome_completo) values (3682668,'mateuscabreira@dpe.rs.gov.br','MATEUS MACHADO CABREIRA');
insert into servidores (matricula, email_servidor, nome_completo) values (3682692,'neliojunior@dpe.rs.gov.br','NELIO MARKS JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (3715116,'carlossantos@dpe.rs.gov.br','CARLOS HENRIQUE RODRIGUES DOS SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3738434,'deborasantos@dpe.rs.gov.br','DEBORA BRANCO AZAMBUJA SANTOS');
insert into servidores (matricula, email_servidor, nome_completo) values (3738442,'ligiacarvalho@dpe.rs.gov.br','LIGIA HELENA FERNANDES CARVALHO');
insert into servidores (matricula, email_servidor, nome_completo) values (3738450,'sabrinasouza@dpe.rs.gov.br','SABRINA BACKES DE SOUZA');
insert into servidores (matricula, email_servidor, nome_completo) values (3738540,'giesacirino@dpe.rs.gov.br','GIESA CARLA CIRINO');
insert into servidores (matricula, email_servidor, nome_completo) values (3757510,'isabelwexel@dpe.rs.gov.br','ISABEL RODRIGUES WEXEL');
insert into servidores (matricula, email_servidor, nome_completo) values (3757528,'alessandravalentini@dpe.rs.gov.br','ALESSANDRA PEDRAZZI VALENTINI');
insert into servidores (matricula, email_servidor, nome_completo) values (3787516,'luisneto@dpe.rs.gov.br','LUIS ERNESTO BASANESI NETO');
insert into servidores (matricula, email_servidor, nome_completo) values (3787532,'arnaldojunior@defensoria.rs.gov.br','ARNALDO FRANCA QUARESMA JUNIOR');
insert into servidores (matricula, email_servidor, nome_completo) values (3787567,'pedrolobo@dpe.rs.gov.br','PEDRO TORRES LOBO');
insert into servidores (matricula, email_servidor, nome_completo) values (3787583,'cibeletonin@dpe.rs.gov.br','CIBELE TONIN STOPPAZZOLLI');
insert into servidores (matricula, email_servidor, nome_completo) values (3815358,'evald-rodrigues@dpe.rs.gov.br','EVALD ELSON GROSSE RODRIGUES');
insert into servidores (matricula, email_servidor, nome_completo) values (3871550,'thiago-goncalves@defensoria.rs.def.br','THIAGO DA SILVEIRA GONCALVES');
insert into servidores (matricula, email_servidor, nome_completo) values (4245148,'silvia-lucas@defensoria.rs.gov.br','SILVIA SCHWANZ LUCAS');

--SELECT 'insert into servidores (matricula, email_servidor, nome_completo) values ('
--      ,matricula
--      ,','
--      ,''''
--      ,email_servidor
--      ,''''
--      ,','
--      ,''''
--      ,nome_completo
--      ,''''
--      ,');'
--  FROM servidores