insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    1   ,   1   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    2   ,   1   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    3   ,   1   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    4   ,   1   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    5   ,   1   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    6   ,   1   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    7   ,   1   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    8   ,   1   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    9   ,   1   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    10  ,   1   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA, SUCESSOES E CURATELAS DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    11  ,   1   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA, SUCESSOES E CURATELAS DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    12  ,   1   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    13  ,   1   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    14  ,   1   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    15  ,   1   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    16  ,   2   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    17  ,   2   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    18  ,   2   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    19  ,   2   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    20  ,   2   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    21  ,   2   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    22  ,   2   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    23  ,   2   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    24  ,   2   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    25  ,   2   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    26  ,   2   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    27  ,   2   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    28  ,   2   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    29  ,   2   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    30  ,   2   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    31  ,   2   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    32  ,   2   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    33  ,   2   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    34  ,   2   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    35  ,   2   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    36  ,   2   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    37  ,   3   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    38  ,   3   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    39  ,   3   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    40  ,   3   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    41  ,   3   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    42  ,   3   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    43  ,   3   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    44  ,   3   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    45  ,   3   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    46  ,   3   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    47  ,   3   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    48  ,   3   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    49  ,   3   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    50  ,   3   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    51  ,   3   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    52  ,   3   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    53  ,   3   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    54  ,   3   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    55  ,   3   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    56  ,   3   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    57  ,   3   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    58  ,   3   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    59  ,   3   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    60  ,   3   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    61  ,   3   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    62  ,   4   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    63  ,   4   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    64  ,   4   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    65  ,   4   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    66  ,   4   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    67  ,   4   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    68  ,   4   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    69  ,   4   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    70  ,   4   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    71  ,   4   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    72  ,   4   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    73  ,   4   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    74  ,   4   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    75  ,   4   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    76  ,   4   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    77  ,   4   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    78  ,   4   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    79  ,   4   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    80  ,   4   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    81  ,   4   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    82  ,   4   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    83  ,   4   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    84  ,   4   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    85  ,   4   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    86  ,   4   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    87  ,   4   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    88  ,   5   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    89  ,   5   ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    90  ,   5   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    91  ,   5   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    92  ,   5   ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    93  ,   5   ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    94  ,   5   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    95  ,   5   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    96  ,   5   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    97  ,   5   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    98  ,   5   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    99  ,   5   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    100 ,   5   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    101 ,   5   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    102 ,   5   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    103 ,   5   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    104 ,   5   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    105 ,   5   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    106 ,   5   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    107 ,   5   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    108 ,   5   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    109 ,   5   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    110 ,   5   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    111 ,   5   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    112 ,   5   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    113 ,   5   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    114 ,   5   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    115 ,   5   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    116 ,   5   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    117 ,   6   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    118 ,   6   ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    119 ,   6   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    120 ,   6   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    121 ,   6   ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    122 ,   6   ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    123 ,   6   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    124 ,   6   ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    125 ,   6   ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    126 ,   6   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    127 ,   6   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    128 ,   6   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    129 ,   6   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    130 ,   6   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    131 ,   6   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    132 ,   6   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    133 ,   6   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    134 ,   6   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    135 ,   6   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    136 ,   6   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    137 ,   6   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    138 ,   6   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    139 ,   6   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    140 ,   6   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    141 ,   6   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    142 ,   6   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    143 ,   6   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    144 ,   6   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    145 ,   6   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    146 ,   6   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    147 ,   6   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    148 ,   7   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    149 ,   7   ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    150 ,   7   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    151 ,   7   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    152 ,   7   ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    153 ,   7   ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    154 ,   7   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    155 ,   7   ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    156 ,   7   ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    157 ,   7   ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    158 ,   7   ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    159 ,   7   ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    160 ,   7   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    161 ,   7   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    162 ,   7   ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    163 ,   7   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    164 ,   7   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    165 ,   7   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    166 ,   7   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    167 ,   7   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    168 ,   7   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    169 ,   7   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    170 ,   7   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    171 ,   7   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    172 ,   7   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    173 ,   7   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    174 ,   7   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    175 ,   7   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    176 ,   7   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    177 ,   7   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    178 ,   7   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    179 ,   7   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    180 ,   7   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    181 ,   7   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    182 ,   7   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    183 ,   8   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    184 ,   8   ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    185 ,   8   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    186 ,   8   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    187 ,   8   ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    188 ,   8   ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    189 ,   8   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    190 ,   8   ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    191 ,   8   ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    192 ,   8   ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    193 ,   8   ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    194 ,   8   ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    195 ,   8   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    196 ,   8   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    197 ,   8   ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    198 ,   8   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    199 ,   8   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    200 ,   8   ,   83  ,   '4a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    201 ,   8   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    202 ,   8   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    203 ,   8   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    204 ,   8   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    205 ,   8   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    206 ,   8   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    207 ,   8   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    208 ,   8   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    209 ,   8   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    210 ,   8   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    211 ,   8   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    212 ,   8   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    213 ,   8   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    214 ,   8   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    215 ,   8   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    216 ,   8   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    217 ,   8   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    218 ,   8   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    219 ,   9   ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    220 ,   9   ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    221 ,   9   ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    222 ,   9   ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    223 ,   9   ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    224 ,   9   ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    225 ,   9   ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    226 ,   9   ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    227 ,   9   ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    228 ,   9   ,   42  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM EXECUCAO CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    229 ,   9   ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    230 ,   9   ,   54  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    231 ,   9   ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    232 ,   9   ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    233 ,   9   ,   61  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    234 ,   9   ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    235 ,   9   ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    236 ,   9   ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    237 ,   9   ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    238 ,   9   ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    239 ,   9   ,   83  ,   '4a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    240 ,   9   ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    241 ,   9   ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    242 ,   9   ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    243 ,   9   ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    244 ,   9   ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    245 ,   9   ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    246 ,   9   ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    247 ,   9   ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    248 ,   9   ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    249 ,   9   ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    250 ,   9   ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    251 ,   9   ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    252 ,   9   ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    253 ,   9   ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    254 ,   9   ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    255 ,   9   ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    256 ,   9   ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    257 ,   9   ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    258 ,   10  ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    259 ,   10  ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    260 ,   10  ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    261 ,   10  ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    262 ,   10  ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    263 ,   10  ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    264 ,   10  ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    265 ,   10  ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    266 ,   10  ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    267 ,   10  ,   42  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM EXECUCAO CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    268 ,   10  ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    269 ,   10  ,   53  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    270 ,   10  ,   54  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    271 ,   10  ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    272 ,   10  ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    273 ,   10  ,   61  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    274 ,   10  ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    275 ,   10  ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    276 ,   10  ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    277 ,   10  ,   71  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    278 ,   10  ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    279 ,   10  ,   74  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    280 ,   10  ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    281 ,   10  ,   79  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO ALTO PETROPOLIS' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    282 ,   10  ,   81  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    283 ,   10  ,   83  ,   '4a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    284 ,   10  ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    285 ,   10  ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    286 ,   10  ,   89  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA TRISTEZA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    287 ,   10  ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    288 ,   10  ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    289 ,   10  ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    290 ,   10  ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    291 ,   10  ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    292 ,   10  ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    293 ,   10  ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    294 ,   10  ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    295 ,   10  ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    296 ,   10  ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    297 ,   10  ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    298 ,   10  ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    299 ,   10  ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    300 ,   10  ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    301 ,   10  ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    302 ,   10  ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    303 ,   11  ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    304 ,   11  ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    305 ,   11  ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    306 ,   11  ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    307 ,   11  ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    308 ,   11  ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    309 ,   11  ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    310 ,   11  ,   29  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    311 ,   11  ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    312 ,   11  ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    313 ,   11  ,   42  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM EXECUCAO CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    314 ,   11  ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    315 ,   11  ,   53  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    316 ,   11  ,   54  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    317 ,   11  ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    318 ,   11  ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    319 ,   11  ,   61  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    320 ,   11  ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    321 ,   11  ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    322 ,   11  ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    323 ,   11  ,   71  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    324 ,   11  ,   72  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    325 ,   11  ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    326 ,   11  ,   74  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    327 ,   11  ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    328 ,   11  ,   76  ,   'DEFENSORIA PUBLICA ESPECIALIZADA NO ATENDIMENTO A VITIMA DE VIOLENCIA DOMESTICA DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    329 ,   11  ,   79  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO ALTO PETROPOLIS' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    330 ,   11  ,   81  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    331 ,   11  ,   83  ,   '4a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    332 ,   11  ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    333 ,   11  ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    334 ,   11  ,   89  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA TRISTEZA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    335 ,   11  ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    336 ,   11  ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    337 ,   11  ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    338 ,   11  ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    339 ,   11  ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    340 ,   11  ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    341 ,   11  ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    342 ,   11  ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    343 ,   11  ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    344 ,   11  ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    345 ,   11  ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    346 ,   11  ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    347 ,   11  ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    348 ,   11  ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    349 ,   11  ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    350 ,   11  ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    351 ,   12  ,   1   ,   '1a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    352 ,   12  ,   12  ,   '9a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    353 ,   12  ,   13  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    354 ,   12  ,   16  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    355 ,   12  ,   17  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    356 ,   12  ,   21  ,   '13a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    357 ,   12  ,   27  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    358 ,   12  ,   29  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    359 ,   12  ,   31  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    360 ,   12  ,   36  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    361 ,   12  ,   42  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM EXECUCAO CRIMINAL DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    362 ,   12  ,   51  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    363 ,   12  ,   53  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    364 ,   12  ,   54  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    365 ,   12  ,   57  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    366 ,   12  ,   60  ,   '11a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    367 ,   12  ,   61  ,   '2a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    368 ,   12  ,   66  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    369 ,   12  ,   67  ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    370 ,   12  ,   68  ,   '6a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    371 ,   12  ,   69  ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    372 ,   12  ,   71  ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    373 ,   12  ,   72  ,   '4a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    374 ,   12  ,   73  ,   '7a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    375 ,   12  ,   74  ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    376 ,   12  ,   75  ,   '9a DEFENSORIA PUBLICA ESPECIALIZADA EM INFANCIA E JUVENTUDE DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    377 ,   12  ,   76  ,   'DEFENSORIA PUBLICA ESPECIALIZADA NO ATENDIMENTO A VITIMA DE VIOLENCIA DOMESTICA DO FORO CENTRAL'   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    378 ,   12  ,   79  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO ALTO PETROPOLIS' ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    379 ,   12  ,   81  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    380 ,   12  ,   82  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    381 ,   12  ,   83  ,   '4a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON '   ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    382 ,   12  ,   84  ,   '2a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    383 ,   12  ,   85  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    384 ,   12  ,   89  ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA TRISTEZA'    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    385 ,   12  ,   95  ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO 4o DISTRITO '    ,   0   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    386 ,   12  ,   104 ,   '2a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    387 ,   12  ,   105 ,   '5a DEFENSORIA PUBLICA CRIMINAL DE 2o GRAU' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    388 ,   12  ,   106 ,   '1a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    389 ,   12  ,   107 ,   '6a DEFENSORIA PUBLICA CIVEL DE 2o GRAU'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    390 ,   12  ,   108 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    391 ,   12  ,   109 ,   '8a DEFENSORIA PUBLICA ESPECIALIZADA EM AJUIZAMENTO'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    392 ,   12  ,   110 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    393 ,   12  ,   111 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA DO JURI DO FORO CENTRAL'   ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    394 ,   12  ,   112 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA CIVEL DO FORO CENTRAL' ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    395 ,   12  ,   113 ,   '1a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    396 ,   12  ,   114 ,   '3a DEFENSORIA PUBLICA ESPECIALIZADA EM FAMILIA SUCESSOES E CURATELAS DO FORO CENTRAL'  ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    397 ,   12  ,   115 ,   '5a DEFENSORIA PUBLICA ESPECIALIZADA EM PLANTAO CIVEL E DA INFANCIA E JUVENTUDE DE PORTO ALEGRE'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    398 ,   12  ,   116 ,   '3a DEFENSORIA PUBLICA DO FORO REGIONAL DO PARTENON'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    399 ,   12  ,   117 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DA RESTINGA'    ,   1   );
insert into snap_locais (id_linha, id_fechamento, id_local, nome, sem_dono) values (    400 ,   12  ,   118 ,   '1a DEFENSORIA PUBLICA DO FORO REGIONAL DO SARANDI' ,   1   );