insert into servidores (matricula, email_servidor, nome_completo) values
(	1483838	, 'tatiana-fogaca@defensoria.rs.gov.br', 	'TATIANA MARA FOGAÇA'),
(	2459760	, 'ana-rodrigues@defensoria.rs.gov.br', 	'ANA IZABEL MENEZES CHÚ'),
(	2634112	, 'richard-noble@defensoria.rs.gov.br', 	'RICHARD DA SILVA NOBLE'),
(	2699532	, 'tatiana-rodrigues@defensoria.rs.gov.br', 	'TATIANA M. DO NASCIMENTO RODRIGUES'),
(	2714515	, 'eder-soares@defensoria.rs.gov.br', 	'MARCELO FRANÇOIS FELIN'),
(	2754363	, 'silvia-lucas@defensoria.rs.gov.br', 	'ROZINEI DA SILVA DINIZ'),
(	2771900	, 'douglas-correa@defensoria.rs.gov.br', 	'VALQUIRIA BISPO ZORZANELLO'),
(	2803135	, 'andreia-reis@defensoria.rs.gov.br', 	'ANDRÉIA VILLAMIL REIS'),
(	2806835	, 'juliano-amaral@defensoria.rs.gov.br', 	'JULIANO GREFF AMARAL'),
(	2887878	, 'juliana-martins@defensoria.rs.gov.br', 	'JULIANA DA SILVA MARTINS'),
(	3033651	, 'joao-junior@defensoria.rs.gov.br', 	'JOÃO LÚCIO MONTEIRO DE SOUZA JUNIOR'),
(	3040526	, 'marcelo-blanco@defensoria.rs.gov.br', 	'MARCELO ANDRES BLANCO'),
(	3086291	, 'thiago-lobato@defensoria.rs.gov.br', 	'THIAGO BATAIOLI LOBATO'),
(	3091430	, 'luciana-silva@defensoria.rs.gov.br', 	'LUCIANA PINTO DA SILVA'),
(	3389766	, 'camila-mello@defensoria.rs.gov.br', 	'CAMILA SILVA BANDEIRA DE MELLO'),
(	3401758	, 'marilia-santos@defensoria.rs.gov.br', 	'MARILIA ANDRADE DOS SANTOS'),
(	3402940	, 'siselbach@yahoo.com.br', 	'SIMONE SELBACH'),
(	3403700	, 'claudia-rocha@defensoria.rs.gov.br', 	'CLAUDIA ALVES DA ROCHA'),
(	3405117	, 'martha-silveira@defensoria.rs.gov.br', 	'MARTHA SILVEIRA DA SILVEIRA'),
(	3410765	, 'michel-muller@defensoria.rs.gov.br', 	'MICHEL MULLER'),
(	3417247	, 'ana-gomes@defensoria.rs.gov.br', 	'ANA LUÍSA GODOY GOMES'),
(	3418448	, 'daniela-silva@defensoria.rs.gov.br', 	'DANIELA FRANCO REIS E SILVA'),
(	3440214	, 'aline-monteiro@defensoria.rs.gov.br', 	'ALINE RODRIGUES MONTEIRO'),
(	3440346	, 'alicia-walcher@defensoria.rs.gov.br', 	'ALICIA IREBA HERNANDEZ WALCHER'),
(	3444015	, 'thiago-terra@defensoria.rs.gov.br', 	'THIAGO TWEEDIE TERRA'),
(	3446921	, 'patricia-lourenzon@defensoria.rs.gov.br', 	'PATRICIA MIRANDA LOURENZON'),
(	3452034	, 'daiana-pommerening@defensoria.rs.gov.br', 	'DAIANA TESSMANN POMMERENING'),
(	3504859	, 'thomas-vieira@defensoria.rs.gov.br', 	'THOMAS NICOLAS VIEIRA'),
(	3529770	, 'bianca-dullius@defensoria.rs.gov.br', 	'BIANCA FRANCINI DULLIUS'),
(	3570118	, 'douglas-correa@defensoria.rs.gov.br', 	'DOUGLAS CORRÊA DA SILVA'),
(	3577589	, 'carolina-denardin@defensoria.rs.gov.br', 	'CAROLINA CANTARUTTI DENARDIN'),
(	3589285	, 'karen-lima@defensoria.rs.gov.br', 	'KAREN PEREIRA DE LIMA'),
(	3602133	, 'renan-guimaraes@defensoria.rs.gov.br', 	'RENAN ESCHILETTI MACHADO GUIMARÃES'),
(	3608239	, 'heitor-pienis@defensoria.rs.gov.br', 	'HEITOR MARCOS PIENIS'),
(	3624358	, 'daiane-brum@defensoria.rs.gov.br', 	'DAIANE DA SILVEIRA BRUM'),
(	3635627	, 'diego-gabiatti@defensoria.rs.gov.br', 	'DIEGO GABIATTI'),
(	3643557	, 'julia-magdalena@defensoria.rs.gov.br', 	'JULIA GUIMARÃES DE MAGDALENA'),
(	3683990	, 'daiane-benetti@defensoria.rs.gov.br', 	'DAIANE BENETTI'),
(	3722635	, 'ramon-alves@defensoria.rs.gov.br', 	'RAMON PINTO ALVES'),
(	3757641	, 'fabio-rachelle@defensoria.rs.gov.br', 	'FÁBIO SILVEIRA RACHELLE'),
(	3788083	, 'aline-drago@defensoria.rs.gov.br', 	'ALINE FAVERZANI DRAGO'),
(	3801306	, 'rafaela-thiesen@defensoria.rs.gov.br', 	'RAFAELA DALABILIA THIESEN'),
(	3802531	, 'douglas-santin@defensoria.rs.gov.br', 	'DOUGLAS ROBERTO WINKEL SANTIN'),
(	3811271	, 'fernando-cintra@defensoria.rs.gov.br', 	'FERNANDO VOGEL CINTRA'),
(	3814920	, 'aline-rocha@defensoria.rs.gov.br', 	'ALINE ORTIZ DA ROCHA'),
(	3824160	, 'valeria-silva@defensoria.rs.gov.br', 	'VALÉRIA SANTIAGO SILVA'),
(	3846075	, 'rodrigo-goncalves@defensoria.rs.gov.br', 	'RODRIGO JUNG GONÇALVES'),
(	3857735	, 'ana-silveira@defensoria.rs.gov.br', 	'ANA CAROLINA RAMOS SILVEIRA'),
(	3859800	, 'aline-machado@defensoria.rs.gov.br', 	'ALINE MACHADO'),
(	3859819	, 'ricardo-portela@defensoria.rs.gov.br', 	'RICARDO SCORSATTO PORTELA'),
(	3859916	, 'juliana-alves@defensoria.rs.gov.br', 	'JULIANA GARCIA ALVES'),
(	3862941	, 'lucas-kalikowski@defensoria.rs.gov.br', 	'LUCAS VERFE KALIKOWSKI'),
(	3871533	, 'cintia-ribeiro@defensoria.rs.gov.br', 	'CÍNTIA FRANÇA RIBEIRO'),
(	3871541	, 'luana-iserhard@defensoria.rs.gov.br', 	'LUANA BORBA ISERHARD'),
(	3871550	, 'thiago-goncalves@defensoria.rs.gov.br', 	'THIAGO DA SILVEIRA GONÇALVES'),
(	3878139	, 'jonathan-grellert@defensoria.rs.gov.br', 	'JONATHAN REHBEIN GRELLERT'),
(	3878317	, 'tanise-oliveira@defensoria.rs.gov.br', 	'TANISE PIRES DE OLIVEIRA'),
(	3878368	, 'jessica-bauer@defensoria.rs.gov.br', 	'JÉSSICA DOS REIS BAUER'),
(	3878384	, 'cristina-farias@defensoria.rs.gov.br', 	'CRISTINA FARIAS'),
(	3878430	, 'vinicius-santos@defensoria.rs.gov.br', 	'VINICIUS NAHAN DOS SANTOS'),
(	3878449	, 'ronei999gold@gmail.com', 	'RONEI DA SILVA ALMEIDA'),
(	3878813	, 'juliana-laitartt@defensoria.rs.gov.br', 	'JULIANA RABELO CAMPOS LAITARTT'),
(	3878821	, 'regina-carvalho@defensoria.rs.gov.br', 	'REGINA GÜTLER CARVALHO'),
(	3878856	, 'carlos-junior@defensoria.rs.gov.br', 	'CARLOS AUGUSTO LOPES JUNIOR'),
(	3879992	, 'paula-altmann@defensoria.rs.gov.br', 	'PAULA ALTMANN'),
(	3880044	, 'alexandre-matos@defensoria.rs.gov.br', 	'ALEXANDRE LEANDRO PADIAS DE MATOS'),
(	3880052	, 'marcelo-balbom@defensoria.rs.gov.br', 	'MARCELO MARIN BALBOM'),
(	3880346	, 'veyzon-muniz@defensoria.rs.gov.br', 	'VEYZON CAMPOS MUNIZ'),
(	3880354	, 'lisiane-vieira@defensoria.rs.gov.br', 	'LISIANE GONÇALVES RIVERO VIEIRA'),
(	3880397	, 'tobiasbassotto@defensoria.rs.gov.br', 	'TOBIAS RADAELLI BASSOTTO'),
(	3880575	, 'mathias-silva@defensoria.rs.gov.br', 	'MATHIAS JANOVIK DA SILVA'),
(	3880583	, 'matheus-trindade@defensoria.rs.gov.br', 	'MATHEUS TRINDADE'),
(	3880613	, 'maria-gomes@defensoria.rs.gov.br', 	'MARIA GABRIELA GOMES'),
(	3880672	, 'livia-lima@defensoria.rs.gov.br', 	'LÍVIA SUCHY LIMA'),
(	3880753	, 'camila-santos@defensoria.rs.gov.br', 	'CAMILA CARTIER DOS SANTOS'),
(	3880761	, 'daniel-vieira@defensoria.rs.gov.br', 	'DANIEL MOREIRA VIEIRA'),
(	3880770	, 'mariana-marchi@defensoria.rs.gov.br', 	'MARIANA FIGUERA MARCHI'),
(	3880800	, 'marco-rodrigues@defensoria.rs.gov.br', 	'MARCO ANTONIO DE BARROS RODRIGUES'),
(	3880877	, 'brenda-ruviaro@defensoria.rs.gov.br', 	'BRENDA ALBINE SARTORI RUVIARO'),
(	3880885	, 'amanda-gonçalves@defensoria.rs.gov.br', 	'AMANDA REIS GONÇALVES'),
(	3880907	, 'marcelo-merlo@defensoria.rs.gov.br', 	'MARCELO MERLO FLORES'),
(	3880923	, 'diego-fogaça@defensoria.rs.gov.br', 	'DIEGO FERNANDO FOGAÇA TEIXEIRA'),
(	3880931	, 'cristiana-vitoria@defensoria.rs.gov.br', 	'CRISTIANA DA SILVA VITÓRIA'),
(	3880958	, 'aline-oliveira@defensoria.rs.gov.br', 	'ALINE CERUTTI DE OLIVEIRA'),
(	3880974	, 'otavio-otilia@defensoria.rs.gov.br', 	'OTÁVIO DE VARGAS OTILIA'),
(	3880990	, 'joao-sales@defensoria.rs.gov.br', 	'JOÃO VICENTE FERREIRA CAVALHEIRO SALES'),
(	3881024	, 'antonio-fontoura@defensoria.rs.gov.br', 	'ANTÔNIO CARRÉ DA FONTOURA'),
(	3881059	, 'manoela-querino@defensoria.rs.gov.br', 	'MANOELA ANTUNES SITKO QUERINO'),
(	3881210	, 'jessica-antonio@defensoria.rs.gov.br', 	'JÉSSICA DE SOUZA ANTONIO'),
(	3881237	, 'guilermo-rocha@defensoria.rs.gov.br', 	'GUILERMO TIMM ROCHA'),
(	3881334	, 'leticia-lieberknecht@defensoria.rs.gov.br', 	'LETICIA LUIZA LIEBERKNECHT'),
(	3895467	, 'bruna-oliveira@defensoria.rs.gov.br', 	'BRUNA RODRIGUES DE OLVIEIRA'),
(	3895475	, 'janaina-razzera@defensoria.rs.gov.br', 	'JANAINA NUNES RAZZERA'),
(	3895491	, 'julia-sanches@defensoria.rs.gov.br', 	'JULIA JURE DA SILVA SANCHES'),
(	3895505	, 'flavio-junior@defensoria.rs.gov.br', 	'FLAVIO MARTINS RODRIGUES JUNIOR'),
(	3895521	, 'ana-dauve@defensoria.rs.gov.br', 	'ANA CAROLINA DAUVE'),
(	3895530	, 'andre-batista@defensoria.rs.gov.br', 	'ANDRE LUIS LUCERO BATISTA'),
(	3895548	, 'anne-favero@defensoria.rs.gov.br', 	'ANNE BEATRIZ FAVERO'),
(	3895556	, 'benhur-laurentino@defensoria.rs.gov.br', 	'BENHUR SALINI LAURENTINO'),
(	3895572	, 'bruna-silva@defensoria.rs.gov.br', 	'BRUNA CASALI DA SILVA'),
(	3895580	, 'bruno-heis@defensoria.rs.gov.br', 	'BRUNO DALPIAN HEIS'),
(	3895610	, 'celia-poa@yahoo.com.br', 	'CÉLIA MURUSSI SILVEIRA'),
(	3895637	, 'daiane-strack@defensoria.rs.gov.br', 	'DAIANE KLOCKNER STRACK'),
(	3895661	, 'douglas-santos@defensoria.rs.gov.br', 	'DOUGLAS EVANDRO SANTOS'),
(	3895670	, 'eduardo-silva@defensoria.rs.gov.br', 	'EDUARDO MACHADO SILVA'),
(	3895688	, 'fernanda-alves@defensoria.rs.gov.br', 	'FERNANDA DIAS ALVES'),
(	3895696	, 'fernanda-silva@defensoria.rs.gov.br', 	'FERNANDA TEDESCO SILVA'),
(	3895700	, 'gabriela-scheeren@defensoria.rs.gov.br', 	'GABRIELA SCHEEREN'),
(	3895718	, 'cassia-dias@defensoria.rs.gov.br', 	'CASSIA LOPES DA SILVEIRA DIAS'),
(	3895734	, 'gessica-camara@defensoria.rs.gov.br', 	'GESSICA PACHECO CAMARA'),
(	3895793	, 'joel-oliveira@defensoria.gov.rs', 	'JOEL MÓISES DE OLIVEIRA'),
(	3895858	, 'lorena-souza@defensoria.rs.gov.br', 	'LORENA PINTO DE SOUZA'),
(	3895866	, 'denise-stohlirck@defensoria.rs.gov.br', 	'DENISE STOHLIRCK'),
(	3895882	, 'luana-castro@defensoria.rs.gov.br', 	'LUANA CHAGAS CASTRO'),
(	3895904	, 'luciano-destro@defensoria.rs.gov.br', 	'LUCIANO SESTI DESTRO'),
(	3895920	, 'lucien-pires@defensoria.rs.gov.br', 	'LUCIEN CARLOS SILVEIRA PIRES'),
(	3895947	, 'marcell-silva@defensoria.rs.gov.br', 	'MARCELL DO AMARAL SILVA'),
(	3895998	, 'maria-costa@defensoria.rs.gov.br', 	'MARIA LUIZA DA COSTA'),
(	3896021	, 'alessandra-pereira@defensoria.rs.gov.br', 	'ALESSANDRA DOS SANTOS PEREIRA'),
(	3896030	, 'natasha-bard@defensoria.rs.gov.br', 	'NATASHA LIS STREIT BARD'),
(	3896048	, 'maximiliano-kegler@defensoria.rs.gov.br', 	'MAXIMILIANO BORDIM KEGLER'),
(	3896099	, 'priscila-pinto@defensoria.rs.gov.br', 	'PRISCILA ROUSANI PINTO'),
(	3896102	, 'daniel-caye@defensoria.rs.gov.br', 	'DANIEL PAULO CAYE'),
(	3896110	, 'renata-mussi@defensoria.rs.gov.br', 	'RENATA LUIZ MUSSI'),
(	3896129	, 'tais-coimbra@defensoria.rs.gov.br', 	'TAYLA MACHADO CARVALHO'),
(	3896137	, 'rosane-breier@defensoria.rs.gov.br', 	'ROSANE PORTO BREIER'),
(	3896153	, 'tafate-dias@defensoria.rs.gov.br', 	'TAFATE VIANA DIAS VILELA'),
(	3896188	, 'carla-comette@defensoria.rs.gov.br', 	'CARLA COMETTE'),
(	3896196	, 'vania-pazdiora@defensoria.rs.gov.br', 	'VÂNIA CARLA PAZDIORA'),
(	3896200	, 'tais-coimbra@defensoria.rs.gov.br', 	'TAIS VASCONCELOS COIMBRA'),
(	3896218	, 'vinicius-carvalho@defensoria.rs.gov.br', 	'VINICIUS DOS SANTOS CARVALHO'),
(	3896234	, 'talita-flores@defensoria.rs.gov.br', 	'TALITA BOTEGA FLORES'),
(	3896250	, 'marilia-almeida@defensoria.rs.gov.br', 	'MARILIA CASANOVA DE ALMEIDA'),
(	3896323	, 'juliano-maffazioli@defensoria.rs.gov.br', 	'JULIANO DE NARDO MAFFAZIOLI'),
(	3896374	, 'lauren-muller@defensoria.rs.gov.br', 	'LAUREN WILLERS MULLER'),
(	3896455	, 'AROLDOVIECILI@YAHOO.COM.BR', 	'AROLDO VIECILI'),
(	3896463	, 'rosane-correa@defensoria.rs.gov.br', 	'ROSANE DA ROSA CORREA'),
(	3896536	, 'lucas-brito@defensoria.rs.gov.br', 	'LUCIANA DULLIUS FRAGA'),
(	3896676	, 'deniselli-feltrin@defensoria.rs.gov.br', 	'DENISELLI LOPES AYRES FELTRIN'),
(	3902315	, 'alana-brixner@defensoria.rs.gov.br', 	'ALANA EVELINE BRIXNER'),
(	3903141	, 'patrick-alves@defensoria.rs.gov.br', 	'PATRICK LIMA FERNANDES ALVES'),
(	3904873	, 'adrian-tapada@defensoria.rs.gov.br', 	'ADRIAN ABI TAPADA'),
(	3920887	, 'stephanie-serafini@defensoria.rs.gov.br', 	'STEPHANIE VILELA SERAFINI'),
(	3920984	, 'telma-fraga@defensoria.rs.gov.br', 	'TELMA CORREA DE FRAGA'),
(	3921131	, 'thamyz-peres@defensoria.rs.gov.br', 	'THAMYZ BRITO PERES'),
(	3921212	, 'thierre-veiga@defensoria.rs.gov.br', 	'THIERRE MIRANDA DA VEIGA'),
(	3921387	, 'vander-madrid@defensoria.rs.gov.br', 	'VÂNDER LUIS DA SILVA MADRID'),
(	3921840	, 'luiza-christmann@defensoria.rs.gov.br', 	'LUIZA CHRISTMANN'),
(	3921948	, 'jeferson-bertolo@defensoria.rs.gov.br', 	'JEFERSON LUIZ BERTOLO'),
(	3922120	, 'ananda-longo@defensoria.rs.gov.br', 	'ANANDA LONGO'),
(	3922162	, 'anderson-schorr@defensoria.rs.gov.br', 	'ANDERSON LUIZ MATTOS SCHORR'),
(	3922200	, 'arnaldo-neto@defensoria.rs.gov.br', 	'ARNALDO ALVES PEREIRA NETO'),
(	3922243	, 'cristiane-reis@defensoria.rs.gov.br', 	'CRISTIANE AZEVEDO DOS REIS'),
(	3925099	, 'everton-bartz@defensoria.rs.gov.br', 	'EVERTON FRANCIS PEREIRA MADRUGA BARTZ'),
(	3925226	, 'bruno-liedtke@defensoria.rs.gov.br', 	'BRUNO LIEDTKE'),
(	3925307	, 'carolina-campos@defensoria.rs.gov.br', 	'CAROLINA SILVA COSTA ILHEU CAMPOS'),
(	3925447	, 'caroline-cardoso@defensoria.rs.gov.br', 	'CAROLINE MARQUES CARDOSO'),
(	3925544	, 'clareana-ferreira@defensoria.rs.gov.br', 	'CLAREANA KUNZLER FERREIRA'),
(	3925609	, 'emely-lubschinski@defensoria.rs.gov.br', 	'EMELY LUBSCHINSKI'),
(	3925668	, 'fernando-araujo@defensoria.rs.gov.br', 	'FERNANDO SANGOI ARAÚJO'),
(	3925811	, 'humberto-ribeiro@defensoria.rs.gov.br', 	'HUMBERTO BORGES RIBEIRO'),
(	3926141	, 'mariana-buckowski@defensoria.rs.gov', 	'MARIANA BUCKOWSKI'),
(	3926206	, 'paulo-silva@defensoria.rs.gov.br', 	'PAULO JEFFERSON SOUSA DA SILVA'),
(	3926290	, 'suelen-canal@defensoria.rs.gov.br', 	'SUELEN CANAL'),
(	3937534	, 'daniela-luca@defensoria.rs.gov.br', 	'DANIELA DE LUCA'),
(	3939499	, 'rodrigo-bueno@defensoria.rs.gov.br', 	'RODRIGO GALVÃO BUENO'),
(	3941604	, 'andreia-rocha@defensoria.rs.gov.br', 	'ANDREIA ALVES ROCHA'),
(	3941680	, 'caio-paiva@defensoria.rs.gov.br', 	'CAIO EDUARDO LUGRIS PAIVA'),
(	3941728	, 'cassiano-mendes@defensoria.rs.gov.br', 	'CASSIANO GONÇALVES MENDES'),
(	3941779	, 'claudia-karsburg@defensoria.rs.gov.br', 	'CLAUDIA DA ROSA KARSBURG'),
(	3941795	, 'elisa-bosner@defensoria.rs.gov.br', 	'ELISA RUMI BOSNER'),
(	3941809	, 'eloisa-mangini@defensoria.rs.gov.br', 	'ELOISA MANGINI'),
(	3941817	, 'angela-genro@defensoria.rs.gov.br', 	'ANGELA SAIDELES GENRO'),
(	3941833	, 'fernanda-goldenfum@defensoria.rs.gov.br', 	'FERNANDA PEIXOTO GOLDENFUM'),
(	3941841	, 'gustavo-knopp@defensoria.rs.gov.br', 	'GUSTAVO CARLOS COUTO KNOPP'),
(	3941884	, 'leticia-rue@defensoria.rs.gov.br', 	'LETÍCIA ALMEIDA DE LA RUE'),
(	3941892	, 'gustavo-jesus@defensoria.rs.gov.br', 	'GUSTAVO ALVES DE JESUS'),
(	3941914	, 'pamela-rosa@defensoria.rs.gov.br', 	'PAMELA CAROLINE DA ROSA'),
(	3941965	, 'arthur-azambuja@defensoria.rs.gov.br', 	'ARTHUR DE AZAMBUJA'),
(	3942104	, 'roberta-santos@defensoria.rs.gov.br', 	'ROBERTA ANTONIOLI SÓ DOS SANTOS'),
(	3942163	, 'krystoffer-bakof@defensoria.rs.gov.br', 	'KRYSTOFFER ROQUE BAKOF'),
(	3942694	, 'ana-pereira@defensoria.rs.gov.br', 	'ANA PAULA VARGAS PEREIRA'),
(	3942791	, 'leonardo-aurich@defensoria.rs.gov.br', 	'LEONARDO AURICH'),
(	3942830	, 'flavia-mattos@defensoria.rs.gov.br', 	'FLÁVIA DE MELO DA ROCHA MATTOS'),
(	3942953	, 'carla-sousa@defensoria.rs.gov.br', 	'CARLA VERENA DO NASCIMENTO SOUSA'),
(	3943062	, 'elis-miranda@defensoria.rs.gov.br', 	'ELIS REGINA DE SOUSA MIRANDA'),
(	3943194	, 'larissa-agnol@defensoria.rs.gov.br', 	'LARISSA AVENA DALL AGNOL'),
(	3950506	, 'solange-rydz@defensoria.rs.gov.br', 	'SOLANGE GOMES DA SILVA RYDZ'),
(	3963837	, 'sara-dockhorn@defensoria.rs.gov.br', 	'SARA ELIZE DE ALMEIDA DOCKHORN'),
(	3964434	, 'gilcea-silva@defensoria.rs.gov.br', 	'GILCÉA DA GLÓRIA SILVA'),
(	3964450	, 'marcela-andreata@defensoria.rs.gov.br', 	'MARCELA VALADARES GONTIJO ANDREATA'),
(	3964523	, 'huberto-timm@defensoria.rs.gov.br', 	'HUBERTO MATHIAS TIMM'),
(	3965112	, 'cristiano-pegorini@defensoria.rs.gov.br', 	'CRISTIANO DE AZEREDO PEGORINI'),
(	3965155	, 'anelise-cornelio@defensoria.rs.gov.br', 	'ANELISE FONTANA CORNELIO'),
(	3965333	, 'mariany-machado@defensoria.rs.gov.br', 	'MARIANY HAYGERT MACHADO'),
(	3965392	, 'mauricio-correa@defensoria.rs.gov.br', 	'MAURÍCIO MENDES CORRÊA'),
(	3965414	, 'nathalie-ferreira@defensoria.rs.gov.br', 	'NATHALIE GUT FERREIRA'),
(	3965422	, 'paulo-rodrigues@defensoria.rs.gov.br', 	'PAULO RICARDO DE MOURA RODRIGUES'),
(	3965635	, 'catiane-norbert@defensoria.rs.gov.br', 	'CATIANE TEIXEIRA REIS NORBERT'),
(	3965643	, 'diego-nascimento@defensoria.rs.gov.br', 	'DIEGO NASCIMENTO DA SILVA'),
(	3965660	, 'fabiane-russi@defensoria.rs.gov.br', 	'FABIANE GARCIA RUSSI'),
(	3965708	, 'felipe-wild@defensoria.rs.gov.br', 	'FELIPE WILD'),
(	3965716	, 'grace-villanova@defensoria.rs.gov.br', 	'GRACE VIVIANE FRIGO VILLA NOVA'),
(	3965759	, 'rafaela-moraes@defensoria.rs.gov.br', 	'RAFAELA SANTIAGO MORAES'),
(	3965856	, 'sissi-holderried@defensoria.rs.gov.br', 	'SISSI HOLDERRIED'),
(	3965872	, 'karen-berton@deefnsoria.rs.gov.br', 	'KAREN ROCHA DA ROSA BERTON'),
(	3965899	, 'cristopher-vidor@defensoria.rs.gov.br', 	'CRISTOPHER ALEXANDER MARTINS VIDOR'),
(	3965970	, 'julio-souza@defensoria.rs.gov.br', 	'JULIO ODRACIR OLIVEIRA DE SOUZA'),
(	3966046	, 'daniel-boeira@defensoria.rs.gov.br', 	'DANIEL DE OLIVEIRA BOEIRA'),
(	3966089	, 'rafael-munsberg@defensoria.rs.gov.br', 	'RAFAEL BECKER STEFFEN MUNSBERG'),
(	3966410	, 'carlos-monteiro@defensoria.rs.gov.br', 	'CARLOS MAURÍCIO MONTEIRO'),
(	3966658	, 'valeria-sisson@defensoria.rs.gov.br', 	'VALÉRIA ZANARDO SISSON'),
(	3966895	, 'marcelo-lopes@defensoria.rs.gov.br', 	'MARCELO GONÇALVES LOPES'),
(	3967069	, 'jussara-abrao@defensoria.rs.gov.br', 	'JUSSARA FERREIRA ABRÃO MACIEL'),
(	3967140	, 'jose-junior@defensoria.rs.gov.br', 	'JOSÉ CARLOS MORAES TRINDADE JÚNIOR'),
(	3967182	, 'luiz-santos@defensoria.rs.gov.br', 	'LUIZ DARCI MARTINS DOS SANTOS'),
(	3967387	, 'bruno-hahn@defensoria.rs.gov.br', 	'BRUNO BOFF HAHN'),
(	3967409	, 'claudia-bergamin@defensoria.rs.gov.br', 	'CLÁUDIA REGINA GALINA BERGAMIN'),
(	3967433	, 'luiz-lorenci@defensoria.rs.gov.br', 	'LUIZ FERNANDO LORENCI'),
(	3968200	, 'marjorie-teixeira@defensoria.rs.gov.br', 	'MARJORIE FÁTIMA BECK TEIXEIRA'),
(	3968243	, 'andrea-born@dpe.rs.gov.br', 	'ANDRÉA STORCH BORN'),
(	3968502	, 'aline-silva@defensoria.rs.gov.br', 	'ALINE AMARAL DA SILVA'),
(	3971945	, 'alessandra-francisco@defensoria.rs.gov.br', 	'ALESSANDRA GIL FRANCISCO'),
(	3971996	, 'ana-brandao@defensoria.rs.gov.br', 	'ANA FLÁVIA COSTA BRANDÃO'),
(	3972151	, 'bibiana-lucas@defensoria.rs.gov.br', 	'BIBIANA DE BORBA LUCAS'),
(	3972186	, 'carla-alimena@defensoria.rs.gov.br', 	'CARLA MARRONE ALIMENA'),
(	3972313	, 'carolina-moraes@defensoria.rs.gov.br', 	'CAROLINA FELKER MORAES'),
(	3972356	, 'carlos-pozzer@defensoria.rs.gov.br', 	'CARLOS LUTZ POZZER'),
(	3972399	, 'clair-ferreira@defensoria.rs.gov.br', 	'CLAIR BALHEGO FERREIRA'),
(	3972470	, 'dante-melero@defensoria.rs.gov.br', 	'DANTE LISANDRO DE OLIVEIRA MELERO'),
(	3972488	, 'edegar-junior@defensoria.rs.gov.br', 	'EDEGAR RIBEIRO JÚNIOR'),
(	3972496	, 'everton-gaspar@defensoria.rs.gov.br', 	'EVERTON GASPAR'),
(	4197836	, 'felipe-franceschette@defensoria.rs.gov.br', 	'FELIPE RENE FRANCESCHETTE'),
(	4197895	, 'guilherme-thome@defensoria.rs.gov.br', 	'GUILHERME BISÓL THOMÉ'),
(	4197917	, 'gustavo-bertoldi@defensoria.rs.gov.br', 	'GUSTAVO FONSECA BERTOLDI'),
(	4199057	, 'lenise-santos@defensoria.rs.gov.br', 	'LENISE ALVES SANTOS'),
(	4199081	, 'luana-dalosto@defensoria.rs.gov.br', 	'LUANA DALOSTO'),
(	4199103	, 'lucciele-lanza@defensoria.rs.gov.br', 	'LUCCIELE SILVA LANZA'),
(	4199111	, 'rafael-haas@defensoria.rs.gov.br', 	'RAFAEL CRIVELARO HAAS'),
(	4199146	, 'luiza-przybylski@defensoria.rs.gov.br', 	'LUIZA NORTHFLEET PRZYBYLSKI'),
(	4199162	, 'marcelly-signoretti@defensoria.rs.gov.br', 	'MARCELLY CHRISTIANE GOULART SIGNORETTI'),
(	4199170	, 'regis-silva@defensoria.rs.gov.br', 	'RÉGIS SCHNEIDER DA SILVA'),
(	4199189	, 'marcio-fagundes@defensoria.rs.gov.br', 	'MARCIO NASCIMENTO FAGUNDES'),
(	4199197	, 'renata-fontoura@defensoria.rs.gov.br', 	'RENATA GABRIELA HECKLER DA FONTOURA'),
(	4199227	, 'rodrigo-borba@defensoria.rs.gov.br', 	'RODRIGO ALVES BORBA'),
(	4199251	, 'rute-mello@defensoria.rs.gov.br', 	'RUTE ANTUNES DE MELLO'),
(	4199308	, 'tatiane-spironello@defensoria.rs.gov.br', 	'TATIANE AZEVEDO SPIRONELLO'),
(	4199332	, 'mariane-ceconello@defensoria.rs.gov.br', 	'MARIANE TRAVI CECONELLO'),
(	4199391	, 'nidiara-medeiros@defensoria.rs.gov.br', 	'NIDIARA DENARDI MEDEIROS'),
(	4199529	, 'bruna-farias@defensoria.rs.gov.br', 	'BRUNA PEREIRA FARIAS'),
(	4199545	, 'camila-lago@defensoria.rs.gov.br', 	'CAMILA DAL LAGO'),
(	4199553	, 'douglas-souza@defensoria.rs.gov.br', 	'DOUGLAS LIMA DE SOUZA'),
(	4199561	, 'thales-lang@defensoria.rs.gov.br', 	'THALES KATSUO SAITO LANG'),
(	4199588	, 'tiago-martins@defensoria.rs.gov.br', 	'TIAGO MARTINS DOS SANTOS'),
(	4199600	, 'fernando-taschetto@defensoria.rs.gov.br', 	'FERNANDO MAICON PRADO TASCHETTO'),
(	4199634	, 'laura-silveira@defensoria.rs.gov.br', 	'LAURA PEREIRA DA SILVEIRA'),
(	4199669	, 'nathalia-gonzales@defensoria.rs.gov.br', 	'NATHALIA NASCIMENTO ECOS GONZALES'),
(	4199855	, 'samuel-costa@defensoria.rs.gov.br', 	'SAMUEL TELLES COSTA'),
(	4199928	, 'yasha-gallazzi@defensoria.rs.gov.br', 	'YASHÁ JOSÉ RIZZANTE GALLAZZI'),
(	4199944	, 'vanessa-nicolao@defensoria.rs.gov.br', 	'VANESSA NICOLAO'),
(	4208072	, 'ada-rodrigues@defensoria.rs.gov.br', 	'ADA SATHLER  RODRIGUES'),
(	4208153	, 'rodrigo-remonti@defensoria.rs.gov.br', 	'RODRIGO AUATT PAES REMONTI'),
(	4208161	, 'sandra-marroni@defensoria.rs.gov.br', 	'SANDRA MARILISE WENTZ MARRONI'),
(	4208188	, 'vinicius-basso@defensoria.rs.gov.br', 	'VINICIUS BASSO DOS SANTOS'),
(	4208358	, 'catarina-rohr@defensoria.rs.gov.br', 	'CATARINA ROHR'),
(	4208382	, 'eder-yabel@defensoria.rs.gov.br', 	'ÉDER JACKSON DOS SANTOS YABEL'),
(	4208439	, 'eduardo-schreiber@defensoria.rs.gov.br', 	'EDUARDO FONTES SCHREIBER'),
(	4209125	, 'marilia-todeschini@defensoria.rs.gov.br', 	'MARÍLIA LUÍSA ROZEC TODESCHINI'),
(	4209141	, 'nadja-silva@defensoria.rs.gov.br', 	'NADJA GONÇAVES DA SILVA'),
(	4209150	, 'nelson-altmann@defensoria.rs.gov.br', 	'NELSON FERNANDO ALTMANN'),
(	4214803	, 'aquila-carvalho@defensoria.rs.gov.br', 	'ÁQUILA DE PAULA POSTIGUILHONE CARVALHO'),
(	4214838	, 'andre-silveira@defensoria.rs.gov.br', 	'ANDRÉ DA SILVEIRA'),
(	4214870	, 'camila-copetti@defensoria.rs.gov.br', 	'CAMILA COPETTI'),
(	4214897	, 'debora-rigon@defensoria.rs.gov.br', 	'DÉBORA DA SILVA RIGON'),
(	4214900	, 'josiel-vicente@defensoria.rs.gov.br', 	'JOSIEL VICENTE'),
(	4214919	, 'marilia-gazal@defensoria.rs.gov.br', 	'MARÍLIA DE OLIVEIRA GAZAL'),
(	4214927	, 'felipe-silva@defensoria.rs.gov.br', 	'FELIPE GALHARDO BARBOSA SILVA'),
(	4214943	, 'fernanda-cerqueira@defensoria.rs.gov.br', 	'FERNANDA SECCHI CERQUEIRA'),
(	4214951	, 'rafael-arsand@defensoria.rs.gov.br', 	'RAFAEL ARSAND'),
(	4214960	, 'rodrigo-weirich@defensoria.rs.gov.br', 	'RODRIGO AHLERT WEIRICH'),
(	4214986	, 'liara-terra@defensoria.rs.gov.br', 	'LIARA JAMILI DUARTE TERRA'),
(	4214994	, 'neith-freire@defensoria.rs.gov.br', 	'NEITH MARIA KROEFF BARBOSA FREIRE'),
(	4215001	, 'victor-franco@defensoria.rs.gov.br', 	'VICTOR CARNIATO FRANCO'),
(	4215010	, 'patricia-vasconselos@defensoria.rs.gov.br', 	'PATRÍCIA ALMEIDA VASCONSELOS'),
(	4215036	, 'vinicius-mendonca@defensoria.rs.gov.br', 	'VINÍCIUS MOREIRA MENDONÇA'),
(	4215044	, 'vladmir-policena@defensoria.rs.gov.br', 	'VLADMIR IÓRIO POLICENA'),
(	4215249	, 'lisia-brasil@defensoria.rs.gov.br', 	'LISIA DA SILVA BRASIL'),
(	4215273	, 'juliana-melo@defensoria.rs.gov.br', 	'JULIANA FREITAS DE MELO'),
(	4215648	, 'matheus-carazzo@defensoria.rs.gov.br', 	'MATHEUS SCHAFER CARAZZO'),
(	4222563	, 'ana-maciel@defensoria.rs.gov.br', 	'ANA AMÉLIA MACIÉL'),
(	4222580	, 'gabriel-regla@defensoria.rs.gov.br', 	'GABRIEL REGLA'),
(	4222598	, 'guilherme-goncalves@defensoria.rs.gov.br', 	'GUILHERME OSTJEN GONÇALVES'),
(	4222610	, 'aline-guillante@defensoria.rs.gov.br', 	'ALINE GUILLANTE'),
(	4222644	, 'bianca-hartwig@defensoria.rs.gov.br', 	'BIANCA CENTURION HARTWIG'),
(	4222652	, 'camila-mansur@defensoria.rs.gov.br', 	'CAMILA BELTRAME MANSUR'),
(	4222660	, 'clenio-gabe@defensoria.rs.gov.br', 	'CLENIO LUIS GABE'),
(	4222679	, 'cristian-porto@defensoria.rs.gov.br', 	'CRISTIAN RIBEIRO PORTO'),
(	4222687	, 'fabiano-ferreira@defensoria.rs.gov.br', 	'FABIANO ANDRÉ FERREIRA'),
(	4222695	, 'fernando-morsch@defensoria.rs.gov.br', 	'FERNANDO ALVES MORSCH'),
(	4222709	, 'luan-vanzetto@defensoria.rs.gov.br', 	'LUAN VANZETTO'),
(	4222717	, 'renata-reckziegel@defensoria.rs.gov.br', 	'RENATA BORBA RECKZIEGEL'),
(	4222725	, 'kleiton-matos@defensoria.rs.gov.br', 	'KLEITON DA SILVA MATOS'),
(	4222741	, 'betina-adami@defensoria.rs.gov.br', 	'BETINA DA SILVA ADAMI'),
(	4222750	, 'fernando-rodrigues@defensoria.rs.gov.br', 	'FERNANDO HENRIQUE MELLO RODRIGUES'),
(	4222776	, 'gerdano-neto@defensoria.rs.gov.br', 	'GERDANO DE ABREU NETO'),
(	4222784	, 'lorena-martins@defensoria.rs.gov.br', 	'LORENA SAMPAIO MESQUITA MARTINS'),
(	4222806	, 'karen-floriano@defensoria.rs.gov.br', 	'KAREN CRISTINA LIMA FLORIANO'),
(	4222822	, 'patricia-perpetuo@defensoria.rs.gov.br', 	'PATRÍCIA DAL-BÓ FORTE PERPÉTUO'),
(	4222830	, 'renato-liska@defensoria.rs.gov.br', 	'RENATO COSTAMILAN LISKA'),
(	4222857	, 'maicon-martins@defensoria.rs.gov.br', 	'MAICON CAMARGO MARTINS'),
(	4222865	, 'cezar-rodrigues@defensoria.rs.gov.br', 	'CEZAR AUGUSTO GALLEGO RODRIGUES'),
(	4227174	, 'olga-tamoto@defensoria.rs.gov.br', 	'OLGA TAMOTO'),
(	4227190	, 'thales-peixoto@defensoria.rs.gov.br', 	'THALES SANTIAGO PEIXOTO'),
(	4227204	, 'luana-medeiros@defensoria.rs.gov.br', 	'LUANA BERNARDINES MEDEIROS'),
(	4228308	, 'esmael-fagundes@defensoria.rs.gov.br', 	'ESMAEL PEREIRA FAGUNDES'),
(	4228421	, 'vitor-cunha@defensoria.rs.gov.br', 	'VÍTOR COSTA DA CUNHA'),
(	4228464	, 'suzana-lopes@defensoria.rs.gov.br', 	'SUZANA LOPES'),
(	4230680	, 'luciana-stein@defensoria.rs.gov.br', 	'LUCIANA JUNGUES STEIN'),
(	4230701	, 'debora-jesus@defensoria.rs.gov.br', 	'DEBÓRA VANESS LANDVOIGT DE JESUS'),
(	4245121	, 'eder-soares@defensoria@rs.gov.br', 	'EDER ANDRE SOARES'),
(	4245148	, 'silvia-lucas@defensoria.rs.gov.br', 	'SILVIA SCHWANZ LUCAS');

--SELECT '('
--      ,[matricula]
--      ,', '''+[email_servidor]+''', '
--      ,''''+[nome_completo]+'''),'
--  FROM [db_removal_new_3].[dbo].[servidores]